### ISSUE TITLE
Cannot download mods from linux server

### ISSUE THREAD

**Issue by Herringway** [blushiemagic/tModLoader#119]
When connecting to a linux dedicated server with a different set of mods than the client, the sync never completes. The client displays `Syncing Mods` while the server console prints `Error on message Terraria.MessageBuffer` and no further progress is made. There is no network activity to show anything happening in the background, either.

This happens with any combination of mods.

Using tModLoader 0.9.1 with mono v4.6.1.3 on amd64 linux.

**Comment by Chicken-Bones** [comment]
@JavidPack most likely related to the ordering issue

**Comment by Jofairden** [comment]
@Herringway as cb stated, this is most likely related to an issue present in tML right now. I wanted to notify you that this bug is currently at the top of our priorities list, so it should be fixed in the near future.

**Comment by Herringway** [comment]
good to hear!

**Comment by Jofairden** [comment]
@Chicken-Bones with your latest commits, is this fixed?

**Comment by Chicken-Bones** [comment]
It should be

**Comment by Herringway** [comment]
Tried 0.9.2. Problem still present...

**Comment by Jofairden** [comment]
@Herringway is the problem still present in v0.9.2.2?

**Comment by Herringway** [comment]
it looks like it's been fixed. thank you!

**Comment by Herringway** [comment]
Never mind, I spoke too soon. It gets a little further than it did before, but it still fails to complete.

Mods in use: Thorium mod, Boss checklist, Calamity Mod, Compressed potions, Cosmetic variety & Legends, Crystilium, Prefixes for Enemies, Fargo's Mutant Mod: Summons and Souls, imkSushi Mod, Infinity - Endless Items, Even More Modifiers, Recipe Browser, Reforge Armor, Wing Slot, Wireless, ZoaklenMod

**Comment by AwzemCoffee** [comment]
I am also having this issue. Stuck on "Syncing Mods" and will sit there until the end of time. I tried the server hosting on two different Linux machines. Any help would be greatly appreciated!

**Comment by Herringway** [comment]
No, I cannot reproduce the issue anymore

**Comment by Jofairden** [comment]
Okay well it likely was fixed sometime
