### ISSUE TITLE
Provide elements (along with documentation) to build in-game UI

### ISSUE THREAD

**Issue by Kimi-Arthur** [blushiemagic/tModLoader#131]
We all build some custom UI in mods, but we just randomly use some UI classes that are available, like ItemSlot etc. This includes elements provided in Terraria itself and also elements from tModLoader.

Providing a set of standard elements and some pages in wiki to illustrate when and how to use them will be very helpful. We can provide useful examples in wiki pages, like mimicking the vanilla UI elements (inventory, chest, hotbar etc.) or anything enabled by tModLoader.

**Comment by Jofairden** [comment]
Sort of agree, but it's quite a big undertaking ;)
There's a small UI example in ExampleMod, I also put some of [my own UI](https://github.com/Jofairden/MultiShop) on GH as an example, but lacks thorough documentation. The UI features 2 panels, the left side was meant as a shop/craft panel (craft x item with up to 15 item requirements and/or gold cost + z special slot requirement) and the right panel for 'collectibles'. Hope it helps a bit.

**Comment by JavidPack** [comment]
I think I'll make a widget board for ExampleMod.

**Comment by Kimi-Arthur** [comment]
Yeah, that will take some real work. But should be helpful I guess?

The widget board will be very cool indeed!

**Comment by Chicken-Bones** [comment]
Unless someone is confident that they can implement a quality and decently extensible/comprehensive UI toolkit here, I'd recommend doing it in another mod/library that people can contribute to and use which we'll recommend for the time being

**Comment by Jofairden** [comment]
For future visitors here are sources of UI examples from ExampleMod and other places:
* ExampleMod: [UI](https://github.com/blushiemagic/tModLoader/blob/master/ExampleMod/UI/ExampleUI.cs)
* Cheat sheet: [UI](https://github.com/JavidPack/CheatSheet/tree/master/UI)
* Deconstructor: [UI](https://github.com/Jofairden/TheDeconstructor/tree/master/UI)

UI Tutorial: [Resource bars (TCF)](https://forums.terraria.org/index.php?threads/tutorial-creating-simple-ui-custom-resource-bars.53417/)

Wiki guides for UI are on hold.
