### ISSUE TITLE
Logs.txt file can grow massive

### ISSUE THREAD

**Issue by zauberparacelsus** [blushiemagic/tModLoader#157]
### Description

If it is not manually cleaned up by the user, the Logs.txt file can grow to become massive.  In my case, I as doing a backup of my hard drive, and the backup process started choking on the Logs.txt file due to its size, which was close to a gigabyte.

### Steps to Reproduce

This is something I think would have to occur over time, but chances are that if you've been using tmodloader a while, the Logs.txt file will be very big.

### Expected behavior 

The Logs.txt file should either be periodically deleted, or pruned so that older stuff is deleted from it.

### Actual behavior

Logs.txt is never deleted, cleared, etc.

### Reproduction frequency

It would take a long while to reproduce the issue.

### Versions

tModLoader v0.9.2.2, and probably earlier versions

### Mods

- Alchemist NPC
- Auto Trash
- Boss Checklist
- Cheat Sheet
- Copper Plus
- Dushy's Upgrade
- Experience and Classes
- Fishing 2.0
- imkSushi's Mod
- Endless Pouches and Quivers
- Learn By Doing
- Legend of Terraria 3
- Loot Bags
- Lucky Finish
- More Accessories
- Reforge Armor
- Terra Wings Mod
- Tremor
- Vending Machines
- Wing Slot
- Wireless
- WMITF
- World Gen Previewer
- Zoaklen Mod

### Additional Information

A possible solution would be to use rotating log files between sessions, much like the Firestorm client for Second Life.  IE: with the first session, a Logs.txt file is created, but then on another session, it gets renamed to Logs.1.txt and then a new Logs.txt file replaces it, then on the third session it gets renamed to Logs.2.txt, the current Logs.txt is renamed to Logs.1.txt, and a new Logs.txt is created.  This continues until a maximum number is reached, so for example Logs.5.txt would get deleted instead of being renamed to Logs.6.txt

**Comment by zauberparacelsus** [comment]
The log4net library for .Net could be used to implement log rotation:  https://logging.apache.org/log4net/

**Comment by Bogdan-G** [comment]
You also need a pause before writing something to the log (for example, as it does log4j for Java), otherwise it leads to the delay in starting the game and the drop in FPS in the game.

**Comment by zauberparacelsus** [comment]
I don't think logging has anything to do with long startup times.  During startup, only two entries get added to the Logs.txt file, something to do with buttons.

**Comment by Bogdan-G** [comment]
Create a mod that will spam something into the log.

**Comment by zauberparacelsus** [comment]
And why would I do that?

**Comment by zauberparacelsus** [comment]
I'm not a mod maker.

**Comment by JavidPack** [comment]
I'm thinking we should just clear the logs each startup. I don't see much reason to keep them around, and the messages from previous launches confuse our users who are seeking logs to provide in threads and chats.

Adding a timestamp prefix is also good, but might be unnecessary if we just clear them out on launch. 

Thoughts?

**Comment by Nordblum** [comment]
Only the latest logs file must remain, agreed.

**Comment by Chicken-Bones** [comment]
I vote for timestamps, like `DateTime.Now.ToString("yyyy-MM-dd HHmmss")`
Also only keep the 5 most recent logs

**Comment by Nordblum** [comment]
Maybe only keep the logs after an error occured? What's the point of having logs that say "everything is alright"?

**Comment by Chicken-Bones** [comment]
Our logs file content could probably do with some work but the general idea is
1. provide lots of info on the game state and progression so that the location of an error can be better understood
2. allow mods to add their own log messsages
Logs can often help diagnose other problems that aren't caught exceptions. Especially if the game hard crashes.

**Comment by Nordblum** [comment]
Maybe keep one last log with a timesramp and then 4 more with "_old" added in the end so that users will know exactly what file to send if asked to do so?
