### ISSUE TITLE
blockloot isn't working properly with boss bags

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#169]
Blockloot isn't working properly with boss bags

I think this is still an issue, I was just reminded of this so I thought I should write it down.

**Comment by Jofairden** [comment]
I assume this was for `DropBossBags()`, fixed.

**Comment by JavidPack** [comment]
I'm pretty sure this was about the items in the boss bag. Since we don't call the block loot hook before the bag is opened, we can't block the items that spawn from the bag

**Comment by Jofairden** [comment]
Alright, e1e84f8 should fix this for presents, goodie bags, herb bags, boss bags, crates and lockboxes.

**Comment by Jofairden** [comment]
For future reference: Patch failed earlier, redone. `blockLoot` needed a clear if `PreOpenVanillaBag` fails and after any open hook.
