### ISSUE TITLE
Post Process error while building mod.

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#183]
"I have to make the attribute reference System.Core, rather than mscorlib, but what if, the assembly itself doesn't use System.Core? I didn't import it"

![](https://cdn.discordapp.com/attachments/103114194089431040/319379388103655424/image.png)

Attached test project
[CrashMod.zip](https://github.com/bluemagic123/tModLoader/files/1040647/CrashMod.zip)

**Comment by Chicken-Bones** [comment]
Fixed https://github.com/blushiemagic/tModLoader/commit/ebf30983c432be2c8f0fd8694548eb0f61ef51a1
