### ISSUE TITLE
.twld files should include the full filename from the .wld file, not just the name before the extension

### ISSUE THREAD

**Issue by LikeLakers2** [blushiemagic/tModLoader#196]
Hi, I recently was on the receiving end of a .twld file getting overwritten due to my server host being a bit dumb. Unfortunately, before I had realized it, I had accidentally overwritten both the `.twld` and the `.twld.bak` file -- and me being dumb at the time, I had *just* overwritten the only backups I had. :(

What had happened was that my hosting provider accidentally changed some additional text that got appended to the extension of the `.wld` file (in this case, they used to append ` i386`, so you'd get stuff like `Terraria_Modded.wld i386`; but then they added a ` 1` to the end by pure accident, so it'd be `Terraria_Modded.wld i386 1`; both still ran and loaded fine though). Whilst this wouldn't sound like an issue, that ` 1` at the end made terraria think we wanted to generate a new world, with that ` 1` appended to the end of the filename.

Okay, this is all normal procedure, but unfortunately TML uses only the bit *before* the .wld (or ".wld i386" or whatever) to name the associated .twld files. This meant that my old .twld file was overwritten. In other words, TML would always use `Terraria_Modded.twld` regardless of whether the world we're loading is `Terraria_Modded.wld`, `Terraria_Modded.wld i386`, or `Terraria_Modded.wld i386 1`.

----

What I'd like to suggest is using the full filename before the .twld extension. For example, if a world is named `Blues_Clues.wld`, TML would name it `Blues_Clues.wld.twld`. Or `TMA.wld i386` would result in `TMA.wld i386.twld`. Or `3DS.wld i386 1` would become `3ds.wld i386 1.twld`. You get the point.

I do get that this change might make filenames a bit messy though, and it might also be good to simply change `.twld` to something else, like `.tmw` (Terraria Mod World), but this would solve the issue I had above, and prevent worlds from being overwritten in the event of a server host's fuckup.

Additionally, I understand this is perhaps an isolated incident and that honestly this has a very very slim chance of happening to other users, but I'm still suggesting it because I feel it's something important we could do to prevent users from losing data by accident.

----

Sorry if I'm still supposed to put this in the usual format. If I must, please let me know and I'll reformat this all.

**Comment by Jofairden** [comment]
This sounds like quite a specific issue to me, and I wonder why we should worry much about it.

**Comment by JavidPack** [comment]
Yeah, sounds like your host is doing something extremely wrong and wonky. This is not standard behavior in any computer system I've ever experienced.

Sorry, gonna close.

**Comment by LikeLakers2** [comment]
Wasn't a complaint about an issue my host had -- I was suggesting a solution that TML could implement in the case that this happens elsewhere, whether because of the host or because of the user.

**Comment by Chicken-Bones** [comment]
Sorry about this, while I agree with the decisions of my codevs, I think we could've handled this a little better.

While we'd like to make things as compatible and sensible as possible for everyone, the problem in this case, is that what your host is doing is rather arbitrary. For example, your host may make it `TMA.wld i386` and be happy with `TMA.wld i386.twld` but another host might expect `TMA.wld.twld i386` or something. It's difficult for us to justify what would be an unfortunately convoluted change, on the whims of one server host.

We apologise if this means you're unable to use tModLoader.

**Comment by LikeLakers2** [comment]
Nah, it's fine, it just means I'm having to be more careful with my worlds. I've been taking backups of the world every time before I turn the server on, it works fine.

I understand the logic, however. I will admit it was just the fault of my server host, though.

Thanks. :)
