### ISSUE TITLE
Possible to compile on Linux?

### ISSUE THREAD

**Issue by Teklad** [blushiemagic/tModLoader#197]
I'd really like to help with the Linux port of tModLoader, but I can't seem to find any instructions anywhere related to getting a development environment setup for Linux (if it's even possible).  

Even if a rough draft with details on how I might go about it would enable me to probably write a bash script to ease the process for would-be developers.  I don't care to drudge through the tidbits. :p

Any help with this would be greatly appreciated.  I'm always happy to contribute to a project that interests me. :)

**Comment by raydeejay** [comment]
The main problem is that ILSpy won't run on Mono. If you can get a modded decompiled source from a Windows box, then you should be able to go through the setup tool's source in C# and see how it uses the binaries to work with the patches, and write an equivalent bash script. And at that point you're mostly done, I guess...

I haven't attempted it yet, but that's the gist of it.

**Comment by Teklad** [comment]
When I get some free time I'll do some poking around.  I'm mostly concerned with increasing the stability with tModLoader on Linux.  I get random crashes when opening/closing the mod browser repetitively, or just clicking on "Mods" will set it off sometimes as well. :p 

Outside of that, it runs mostly fine except for the painfully slow mod initialization times on Linux compared to Windows.

**Comment by zauberparacelsus** [comment]
The slowness is due to [performance deficiencies](http://tirania.org/blog/archive/2014/Jul-23.html) in Mono, which can run up to five times slower than .Net.  Since Mono is needed to run .Net applications on non-Windows platforms, Mac and Linux users will be stuck with the performance problems.  You could try running the windows version of Terraria with .Net under WINE, but I don't know how well it will work.

**Comment by JavidPack** [comment]
As for the menu stability problems, I think I have a solution, I was just testing with mono users on the discord. I need to get back to them though.

**Comment by Chicken-Bones** [comment]
There is some consideration for a command line interface for the setup tool, but it is not currently deemed a priority. Aside from this, you have to decompile the windows binary anyway (for consistency) but if you copy the source code across, you should theoretically be able to work on a Linux machine.

**Comment by Teklad** [comment]
@Chicken-Bones Thanks for the insight... I'll setup a VM and try this out... it'll probably take somewhere around forever... but at least I'll be able to make changes. :p
