### ISSUE TITLE
Crash when typing while the downloaded mods list is loading

### ISSUE THREAD

**Issue by imkSushi** [blushiemagic/tModLoader#198]
### Description

When typing in the mods menu (which usually searches all the mods), while the list is loading, the game crashes.

### Steps to Reproduce

1. Enter a world and exit it (otherwise, the mods menu loading time is too short to press a key)
2. Enter the downloaded mods menu
3. Type a letter before it stops loading
4. Crash!

### Expected behavior 

The letter should appear in the search bar, and the list should load as usual

### Actual behavior

The game crashes

### Reproduction frequency

100%

### Versions

tModLoader 0.10.0.1
Windows 10 (updated my PC today in the latest minor win10 update. Crash happened both before and after I updated)

### Mods

Happens with and without any mods enabled

### Additional Information

I have a screenshot of the error dialog after the crash.

![image](https://user-images.githubusercontent.com/16558336/27400690-c701ccea-56b8-11e7-8342-c9e8528ba8de.png)

**Comment by JavidPack** [comment]
Fixed already in https://github.com/blushiemagic/tModLoader/commit/e3fe9e31b299d923e19907def4e3dcd6769de439, which will be in 0.10.0.2
