### ISSUE TITLE
Modloader mod initialization is too slow on linux compared to windows/wine

### ISSUE THREAD

**Issue by Uramekus** [blushiemagic/tModLoader#200]
## Steps to Reproduce

1. download a bunch of mods on linux (big mods like tremor)
2. count the time it needs to initialize
3. do the same on wine/windows and cry that the initialization time is like 5x higher or more depending of cases (using all tmodloader mods it is worse)

### Expected behavior 

faster timings, at least comparable to windows mod initialization time

### Actual behavior

loading times are ridiculous

### Reproduction frequency

100% on my arch and on my gentoo system

### Versions

Latest (10.0.0.1 on 1.3.5.3/2)

### Additional Information

tested on Arch using mono 5.0, mono 4.6, mono 4.4.
tested on Gentoo using 5.0 and 4.8
tested WITH and WITHOUT steam runtime

**Comment by andrefmarques** [comment]
I'm having the same problem. Solus Budgie with last tmodloader.

**Comment by JavidPack** [comment]
Was this tested without using the installed mono?

Either way, I'm not sure what we could do about it, it might be a problem with the runtime itself.

**Comment by PoroCYon** [comment]
Try `mono --profile` (see the mono(1) manpage for more info) to find out what the bottleneck is. (I bet lots of allocations due to memory mismanagement.)

**Comment by zauberparacelsus** [comment]
@PoroCYon How does one execute Terraria with custom mono flags?

Also, the latest version of tmodloader gives some additional info during loading.  On Linux, most of the extra time seems to be spent on loading PNG images.  As I noted on another thread, PNG is ridiculously slow compared to other compressed image formats, so its possible that the mono bindings for libPNG have a ton of overhead.

One possible way to mitigate this problem would be to use threads to load the files, though that could create other issues if the mod files are doing anything extra with the images while loading.

**Comment by PoroCYon** [comment]
@zauberparacelsus Run `Terraria.exe` instead of `Terraria`, and do something like [this](https://github.com/TerrariaPrismTeam/Prism/blob/develop/Prism.sh).

**Comment by Chicken-Bones** [comment]
See if https://github.com/blushiemagic/tModLoader/commit/13d8a2a224abe3e1b690afb2682caf212cb3fcf0 helps at all

**Comment by kennethdhau** [comment]
Was that commit rolled into the latest version?

**Comment by PoroCYon** [comment]
kennethdhau: it should be in v0.10.1.2

**Comment by Chicken-Bones** [comment]
Closing due to lack of discussion
