### ISSUE TITLE
wishlist: add "info accessory" hooks

### ISSUE THREAD

**Issue by slippycheeze** [blushiemagic/tModLoader#202]
I was thinking of throwing together a couple of tiny mods to show some extra info in the game: current fisherman quest state, number of items in play, etc.

The most obvious place to hook that in would be the existing "info" accessories, but checking the decompiled code and existing patches, it doesn't look like there is any scope for hooking into that.

It would be nice to have those: the ability for a mod to define an accessory with an "info" function, and have it show up with the enable/disable button, and the info line, matched with the existing ones.

**Comment by Chicken-Bones** [comment]
Consider submitting a pull request?

**Comment by slippycheeze** [comment]
👍  I'm hoping to be able to do so, but there are a couple of work related legal bars I have to clear first.  Oh, and learning C#. ;)  My vague hope was someone else might already be doing this but, if not, I'll work toward one slowly.

**Comment by Jofairden** [comment]
Im quite sure this can be done by modifying the respective interface layer. Considering the little traction of this issue, I'll go ahead and close this issue. Slippycheeze, if you still end up needing something or having a proposal then feel free to reopen the issue.
