### ISSUE TITLE
Issue Using Mono.Cecil To Modify TModLoader

### ISSUE THREAD

**Issue by RomSteady** [blushiemagic/tModLoader#204]
### Description

If you use another modification package (like RomTerraria/RTRewriter) to modify TModLoader 0.10.0.2, NGEN fails on the generated assembly.

### Steps to Reproduce

1. Install TModLoader 0.10.0.2.  Verify that it is working.
2. Run RTResolution 0.2 from http://romsteady.blogspot.com/2017/06/rtresolution-v02-available-now.html.  While this version of the mod tries to modify two methods (DoDraw and SetGraphicsProfileInternal), only SetGraphicsProfileInternal will be modified due to how TModLoader moves everything over to do_Draw.
3. Move the patched Terraria.exe into the Terraria folder.
4. Launch Terraria.
5. Application crashes with the following error: Method not found: 'System.__Canon System.__Canon[,].Get(Int32, Int32)'.

### Expected behavior 

Application should not crash.

### Actual behavior

The version of Mono.Cecil being used predates the version of the .NET Framework used for TModLoader's compilation.  As a result, things don't work quite right.

### Reproduction frequency

Consistently.

### Versions

v0.10.0.2

### Mods

None

### Additional Information

If you guys want to embed what RTResolution does inside TModLoader, it's easy enough to do.

Inside your revised Terraria.Main::do_Draw(GameTime), there are two constants (1920f and 1200f).  Replace both with 8192f.

Inside Terraria.Main::SetGraphicsProfileInternal(), replace each instance of the constant 4096 with the constant 8192.

**Comment by horsemanV** [comment]
Just commenting to show interest, I love Rom's resolution fix, would love to see it work with TModLoader.

**Comment by Jofairden** [comment]
Isn't this something the patcher should do? (support tModLoader)

**Comment by PoroCYon** [comment]
> Method not found: 'System.__Canon System.__Canon[,].Get(Int32, Int32)'

Sounds like a runtime bogosity: [`System.__Canon` is part of the standard runtime`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Object.cs#L221).

The runtime version used by Mono.Cecil shouldn't be a problem, as it doesn't need any runtime being present for the written assembly -- the work done by Cecil could've been done in native code just fine. It just happens to be written in C#.

-----

OTOH, a stack trace could be useful, as `__Canon` seems to be a runtime utility for a vtable, so it's easier to guess which `Get` method it actually is (i.e. by which type it is owned).

**Comment by Jofairden** [comment]
Commended

**Comment by Kodi4444** [comment]
so is this getting fixed?

**Comment by JavidPack** [comment]
The 0.11 beta is out today with the resolution thing integrated, info is on the discord.

**Comment by Kodi4444** [comment]
What discord?

**Comment by JavidPack** [comment]
Our discord: discord.me/tModLoader

**Comment by Jofairden** [comment]
Discord is a chat app if you weren't aware. We have our own server in it that we use for live chat :)

**Comment by Kodi4444** [comment]
I had no idea that this was already implemented. and to think I've been waiting this whole time for this to be fixed.
