### ISSUE TITLE
monoconfig not found!

### ISSUE THREAD

**Issue by FinlayDaG33k** [blushiemagic/tModLoader#205]
Hii there,  
I made a Linux VM (Debian 8.0) to use as a tModLoader Server.
I installed mono with `apt-get install mono-complete` and waited for it to install.
Not when I run `./tModLoaderServer` I get the error: `monoconfig not found!`

I've looked around on the internet, but nobody else has this issue.
What am I doing wrong?

**Comment by JavidPack** [comment]
Yes, you aren't suppose to install mono. You first install the vanilla server by unzipping the appropriate folder where you want: http://terraria.org/server/terraria-server-1353.zip

And then install tmodloader over that. Then you run the tModLoaderServer script file. (This runs the Terraria-packaged mono, hence you don't need to install mono.)

**Comment by CrazyFrogAxelF** [comment]
I tried this but it still gives me the same error. Is there any other way to fix this... If so could someone please explain???
