### ISSUE TITLE
Best practices?

### ISSUE THREAD

**Issue by Teklad** [blushiemagic/tModLoader#206]
I began working on a companion program for tModLoader a couple of days ago called "tModManager", written in C++, which is meant to be an easy way to launch Terraria, enable/disable/download mods, etc. in a cross-platform manner.

I'm to the point now where I'm able to extract mod data from mods and such (images, audio, etc.)... so I was wondering if there are any practices I should be aware of regarding mod author's data?  

I did notice on default tModLoader some *.tmod files do not extract by author request.  Knowing where that information is kept would be useful as well.

**Comment by Chicken-Bones** [comment]
https://github.com/blushiemagic/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader/BuildProperties.cs

As you can tell, there's nothing stopping a semi-competent dev extracting the content. It's just there to provide a little way to respect the mod author's intents and wishes

**Comment by Teklad** [comment]
@Chicken-Bones after skimming over the binary format of the *.tmod files that became quickly apparent.  I just wanted to make sure to follow some of these practices in order to keep with basic community standards.  I appreciate the link and I'll be sure to incorporate this into my program.  Many thanks. :)
