### ISSUE TITLE
ExampleLaserWeapon is left unfinished

### ISSUE THREAD

**Issue by KanzZz** [blushiemagic/tModLoader#211]
i shoot teh magic tome and nothing comes out nothing 

step 1 go into gaem
step 2 select teh tome
step 3 use tome and notice it does nothing but show particles

**Comment by Jofairden** [comment]
If you mean [this tome](https://github.com/blushiemagic/tModLoader/blob/master/ExampleMod/Items/Weapons/ExampleLaserWeapon.cs), I don't think anyone ever finished it lol.

**Comment by KanzZz** [comment]
also do you know how you change the names of teh items?
