### ISSUE TITLE
Is there an easy way to change the name of the mod?

### ISSUE THREAD

**Issue by KanzZz** [blushiemagic/tModLoader#212]
Id like to change Examplemod to my own custum name how du i du dat

**Comment by JavidPack** [comment]
Change all namespaces and the folder name. Please, however, stop asking support questions here on github. This is for bugs in tModLoader, not for help with modding. Please see https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/ or the discord channel for help: discord.me/tModLoader
