### ISSUE TITLE
2 Errors with enemy spawning.

### ISSUE THREAD

**Issue by DiamondStarmanYT** [blushiemagic/tModLoader#214]
I am new to editing the enemy spawn locations but I don't know what contains the name "info". I also want to know how to make it spawn not specifically at day or night but still have a chance to spawn. Here is the code.

using System;
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ModLoader;
using Terraria.ID;
using Terraria.Localization;
using Terraria.Utilities;
using Terraria.World.Generation;

namespace Skycia.NPCs
{
    public class Darkheart : ModNPC
    {
        public override void SetStaticDefaults()
        {
            DisplayName.SetDefault("Dark Heart");
        }
        public override void SetDefaults()
        {
            npc.width = 48;
            npc.height = 32;
            npc.damage = 68;
            npc.defense = 4;
            npc.lifeMax = 200;
            npc.value = 60f;
            npc.knockBackResist = 0.5f;
            npc.aiStyle = 14;
            npc.HitSound = SoundID.NPCHit1;
            npc.DeathSound = SoundID.NPCDeath1;
            Main.npcFrameCount[npc.type] = 4;
            aiType = 14;  //npc behavior
            animationType = NPCID.Harpy;
            npc.lavaImmune = true;
        }

        public override void FindFrame(int frameHeight)
        {
            npc.frameCounter -= 0.5F; // Determines the animation speed. Higher value = faster animation.
            npc.frameCounter %= Main.npcFrameCount[npc.type];
            int frame = (int)npc.frameCounter;
            npc.frame.Y = frame * frameHeight;

            npc.spriteDirection = npc.direction;
        }
        public override void NPCLoot()  //Npc drop
        {
            {
                Item.NewItem((int)npc.position.X, (int)npc.position.Y, npc.width, npc.height, mod.ItemType("Darksoul"), 1); //Item spawn
            }

        }
        public override float SpawnChance(NPCSpawnInfo spawnInfo)
        {
            return info.spawnTileY > Main.maxTilesY - 190 && Main.hardMode; OverworldNightMonster.Chance * 1f;

        }
    }
}

**Comment by Jofairden** [comment]
Stop asking support questions here on github. This is for bugs in tModLoader, not for help with modding. Please see https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/ or the discord channel for help: discord.me/tModLoader
