### ISSUE TITLE
Multiplayer Projectile Weapons using Projectile.NewProjectile() not syncing until dropped on the ground.

### ISSUE THREAD

**Issue by Cheezegami** [blushiemagic/tModLoader#215]
### Description

When using any king of projectile weapons that spawn in new projectiles using Projectile.NewProjectile() method the projectiles are not being synced in the world, this causes the world / server not to recognize the shots fired, dropping the weapon and picking it up again however seems resolve the issue until reforging and/or leaving and rejoining the server.

### Steps to Reproduce

1. Join a multiplayer server.
2. Get a weapon that spawns a new projectile  utilizing the Projectile.NewProjectile() in the shoot function of a weapon.
3. Shoot any spawned enemy it will not hit them at all.
4. Drop the weapon.
5. Shoot any spawned enemy it should now hit them correctly.

### Expected behavior 

The projectile spawned by Projectile.NewProjectile()  should damage any enemy without requiring it to be dropped at first hand.

### Actual behavior

The projectile spawned by Projectile.NewProjectile() ignores the enemy.

### Reproduction frequency

This issue seems to be at hand with various mod, ranging from spirit mod, to cheeze's content pack.

### Versions

This issue has been apparent ever since I started using tModloader arround 0.8 and now at version 0.10.0.2 it's still apparent.

### Mods

It happens with a variety of mods, even when my own mod (cheeze's content pack) is the only one loaded.

### Additional Information

It has to be in multiplayer.

**Comment by JavidPack** [comment]
I'm guessing the way you set owner in NewProjectile is wrong. You are probably doing item.owner, which you should not do. Use Main.myPlayer. if that is not the issue, seek help in the Terraia community forum or the tmodloader discord, this is not the place for getting help with programming. This is for actual tmodloader bugs.
