### ISSUE TITLE
Terraria Decompiler Outdated

### ISSUE THREAD

**Issue by stefnotch** [blushiemagic/tModLoader#227]
### Description

When decompiling Terraria using the [provided tool](https://github.com/blushiemagic/tModLoader/tree/master/setup/bin) , it complains that the TerrariaServer/Terraria is too new:
`Error: TerrariaServer version 1.3.5.3. Expected 1.3.5.1`
`Error: Terraria version 1.3.5.3. Expected 1.3.5.1`

### Steps to Reproduce

1. Get the latest Terraria version
2. Run `setup.bat`
3. Press on decompile
3. Error happens

### Expected behavior 

That Terraria gets decompiled

### Actual behavior

It complains

### Reproduction frequency

Always

### Versions

Latest

### Mods

n/a

### Additional Information

I would be willing to fix this issue. Though, what bits of code would I have to look at and how do I create those .patch files?

**Comment by Chicken-Bones** [comment]
The only person who can actually fix this is me (and a fix is in the works, but I've been swamped by uni). For now the workaround is to obtain a copy of 1.3.5.1 somehow (consider asking in the Discord)

**Comment by stefnotch** [comment]
:D

However, I'd like to point out that I am perfectly capable of decompiling and fixing Terraria. (I'm one of the authors of Mechmod) In fact, I did it this week. (I only have to sort out one bug regarding the Localisation)

If I can help you somehow, I am willing to do it.

**Comment by Chicken-Bones** [comment]
Fire me a PM on Discord in the next 15 mins

**Comment by stefnotch** [comment]
I'm very sorry, but, I have to go now. Can I do it tomorrow/on some other day?

**Comment by Chicken-Bones** [comment]
Yeah anytime, I'll get back to you there.

**Comment by Kimi-Arthur** [comment]
Seems it's not merged into master? Any ETA for that?

Thanks for the awesome project!

**Comment by Chicken-Bones** [comment]
Unfortunately not, ETA depends on my schedule at the moment

**Comment by Murfalo** [comment]
Hi @stefnotch @Kimi-Arthur @Chicken-Bones - A temporary workaround to this would be to download Terraria 1.3.5.1 from SteamDB using the Steam console:

1. Ensure Steam is closed, then launch Steam using the -console flag.
> "C:\Program Files (x86)\Steam\Steam.exe" -console
2. Navigate to the CONSOLE tab at the top right of Steam and issue the following command:
> download_depot  105600 105601 2659464619157023246
3. Wait until your download has finished.  You can somewhat gauge your progress based on the speeds listed in Steam at Library > Downloads.
4. Copy over the newly downloaded files from SteamDir/SteamApps/content/app_105600/depot_105601 to SteamDir/SteamApps/Terraria.

**Comment by stefnotch** [comment]
Oh, thank you. :D 

Well, I'm already working on getting the decompiler to work with the latest Terraria version. :)
