### ISSUE TITLE
tModLoader does not work when installed on top of the standalone server (rather than the Steam version) on Linux

### ISSUE THREAD

**Issue by Wicloz** [blushiemagic/tModLoader#228]
### Description

Installing tModLoader on top of the Steam files on Linux allows me to host a working server.
Installing it on top of the standalone server (like this one http://terraria.org/server/terraria-server-1353.zip) gives the following error when running: `error while loading shared libraries: libmonosgen-2.0.so.0: cannot open shared object file: No such file or directory`

### Steps to Reproduce

1. Download and extract http://terraria.org/server/terraria-server-1353.zip
2. Install tModLoader on top of it as usual
3. Make sure `tModLoaderServer`, `tModLoaderServer.bin.x86` and `tModLoaderServer.bin.x86_64` are executable.
4. Run `tModLoaderServer`

### Expected behavior 

The server starts succesfully.

### Actual behavior

The following error is given: `error while loading shared libraries: libmonosgen-2.0.so.0: cannot open shared object file: No such file or directory` and the server does not start.

### Reproduction frequency

Every. Single. Time.

### Versions

ModLoader v0.10.0.2
Terraria v1.3.5.3

### Mods

No mods installed.

### Additional Information

Dumping all the files from https://github.com/OutOfOrder/MonoKickstart/tree/master/precompiled on top of the rest allows the server to start but does not allow players to connect.

**Comment by Wicloz** [comment]
Nevermind it was another issue ...

**Comment by JavidPack** [comment]
If you tell me what the other issue was, it would help us help other people with the same issue.

**Comment by Wicloz** [comment]
I was using an older version without noticing ...

**Comment by Wicloz** [comment]
That's why it worked with steam, because I was using another computer and downloaded it again ...
