### ISSUE TITLE
AddMapEntry with an empty ModTranslation crashes

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#230]
The following code in a ModTile crashes/stalls the game:

```
ModTranslation name = CreateMapEntryName();
AddMapEntry(new Color(200, 200, 200), name);
```

The crash happens in LanguageManager.ProcessCopyCommandsInTexts when it comes across a null value for the value in localizedtext.

We need to either ensure that AddMapEntry throws a load error when it has a null value in the ModTranslation's dictionary, have CreateMapEntryName initialize to "" rather than null, or other solutions.

**Comment by Jofairden** [comment]
When the ModTranslation has a null value passed in AddMapEntry, change it to an empty string.
