### ISSUE TITLE
my mod is not working and is enabled?

### ISSUE THREAD

**Issue by prolio14** [blushiemagic/tModLoader#231]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

The tModLoader version should be notified in the bottom left corner when in the main menu. Follow this format: `vX.X.X.X tModLoader` or `tModLoader vX.X.X.X`

**Comment by JavidPack** [comment]
This is not the place to get help with your mod. This is for tModLoader bugs. Visit the forum or the discord channel for help: discord.me/tmodloader
