### ISSUE TITLE
Duplicate .tmod files in Mods folder crashes Mod Browser

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#232]
installedMods.SingleOrDefault in UIModBrowser.PopulateFromJSON throws error when user has multiple .tmod files in the Mods folder with the same internal name. 

Possible solutions

Change
var installed = installedMods.SingleOrDefault(m => m.name == name);
to
var installed = installedMods.FirstOrDefault(m => m.name == name);

or

Change FindMods() to ignore duplicates.

Considerations: how will duplicates impact other areas, such as mod enabling/loading and updates.

**Comment by Chicken-Bones** [comment]
I'll vote for just use the first in the mods browser, but show both in the mods menu, and error if a duplicate on loading

**Comment by Jofairden** [comment]
I think what cb says makes sense, a duplicate error on load seems good. Consider not showing both in the mods menu, the modder might be confused as to why it's not showing.
