### ISSUE TITLE
Request: 1-click mod pack and mod dependency auto-downloads!

### ISSUE THREAD

**Issue by hamstar0** [blushiemagic/tModLoader#236]
Sorry if this is improper form. *They made me do it!*

**Comment by hamstar0** [comment]
If the mod list view added download buttons for mod browser mods, a mod's dependency list (strong; via. build.txt) could be treated _as_ a mod list. Then a mod's dependencies can be downloaded via. the list.

**Comment by Murfalo** [comment]
I was actually just thinking about this!  I'd love to work on getting this implemented.

**Comment by JavidPack** [comment]
Done in e0a8077
