### ISSUE TITLE
TmodLoader not installing on linux.

### ISSUE THREAD

**Issue by Logabe** [blushiemagic/tModLoader#250]
### Description

I'm using a linux computer and i've tried **everything** i can think of, but it still dosn't install TmodLoader.

### Steps to Reproduce
**Use a linux computer**
1. Go into the folder where you saved TmodLoader
2. Open the .jar file with 'Oracle Java 8 Runtime'
3. It say's for me, 'Can't find a place to install!'

### Expected behavior 

Install and ask for passwords and that sort of stuff.

### Actual behavior

It's Pop-ing up a message saying 'Can't find a place to install!'
### Reproduction frequency
It happens every time I open the file

### Versions

I'm using the latest _linux_ Steam TmodLoader.

### Additional Information

I have steam but not terraria. I'm wondering if that's the problem.

**Comment by JavidPack** [comment]
Did you read the readme.txt?

**Comment by JavidPack** [comment]
Then I guess you missed this part:

> If the installer for some reason does not work, or if you do not want to install/upgrade Java, you may also do a manual install.  You may wish to back-up your vanilla Terraria.exe first.
> 
> 1.  Go to your Terraria's Steam folder (the one containing Terraria.exe).  For older installations of Steam, this will be "~/.local/share/Steam/steamapps/common/Terraria".  For newer installations of Steam, this will be "~/.steam/steam/steamapps/common/Terraria".
> 
> 2.  Copy all of these files into that folder.

**Comment by Logabe** [comment]
I did that before I posted the issue. I also **don't** have terraria.

**Comment by JavidPack** [comment]
You don't have Terraria? You can't use tModLoader unless you own Terraria and have it installed. Maybe you should just come to the discord and chat. discord.me/tModLoader
