### ISSUE TITLE
Slowdown in Modbrowser

### ISSUE THREAD

**Issue by Pop000100** [blushiemagic/tModLoader#253]
### Description

massive slowdown when using the mod browser to view certain mods(Logicality is the one i found, both versions)
i suspect its due to the `<br>` tag.

### Steps to Reproduce

1. open mod browser.
2. search Logicality.
3. view it and viola slowdown.

### Expected behavior 

normal menu speed.

### Actual behavior

the background of the main menu slows down.

### Reproduction frequency

100% of the time.

### Versions

tModLoader v0.10.1.0

### Mods
both with and without mods this happens not suprising, since i dont know of any hooks for the main menu yet.

### Additional Information

I3-6100 @ 4.4Ghz
MSI r9 390
Windows 10

**Comment by Jofairden** [comment]
I've actually had this issue myself with Tremor, which was showing <br> tags in the description and lowering my fps to 1. Unknown cause.

**Comment by Luarst** [comment]
I was just about to report this as well since I lag as well with Logicality because of the line-breaks.
