### ISSUE TITLE
It deleted my character and my world

### ISSUE THREAD

**Issue by Gryffinguin** [blushiemagic/tModLoader#254]
When I tried to delete the folder it wouldn't budge and my character and world files are still there but i can't access them in game

**Comment by PoroCYon** [comment]
tModLoader stores its player and world files in a different folder, so modded players/worlds can't be loaded using vanilla.

**Comment by JavidPack** [comment]
https://github.com/blushiemagic/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#help-all-my-players-and-worlds-are-gone
