### ISSUE TITLE
I can't fix the "Terraria.ModLoader.Mod.GetTexture(String name)" error.

### ISSUE THREAD

**Issue by ineedhelp11** [blushiemagic/tModLoader#255]
Everytime I try to reload mods, the mod I created fails to load. Both files have the same name.
![screenshot 139](https://user-images.githubusercontent.com/32588156/31305217-c3f2fe5e-ab66-11e7-8b31-efe7b30885ba.png)

**Comment by JavidPack** [comment]
You should not be asking modding questions here, that is the reason for the discord and the forums.

In this case, you have an extra layer of folders: RalphsMod/RalphsMod. Move everything up a folder.
