### ISSUE TITLE
Creating a new character before joining a friend through Steam prompts the SP World select screen instead

### ISSUE THREAD

**Issue by tomcool2002** [blushiemagic/tModLoader#258]
### Description

I tried to join my friend by using steam but when I create a player , and I choose my player , it ask me to choose a world and that not normal on multiplayer because I join a world not my world
### Steps to Reproduce

1. [launch Terraria]
2. [left click on multiplayer]
3. [left click on join a friend with steam]
4. [right click on the friend you want to join]
5. [left click on join the game]
6. [left click on create a player]
7. [left click on any player ]
8. [and then ther is the world menu even if you are suppose to join someone]
### Expected behavior 

I think it switch your game in singleplayer instead of multiplayer mode when you all ths step

### Actual behavior

I think it switch your game in singleplayer instead of multiplayer mode when you all ths step

### Reproduction frequency

how often that I want

### Versions

v1.3.5.2
tmodloader v0.10.1

### Mods

calamity mod , thorium mod , tremor mod remastered , spirits mod

**Comment by Jofairden** [comment]
The friend should send you an invite which will prompt you to select a player when accepted.

**Comment by tomcool2002** [comment]
yes but the problem is after selecting a player because my friend's world not mine

**Comment by tomcool2002** [comment]
because I want to join my friend's world not mine*

**Comment by JavidPack** [comment]
Yeah, I've experience this too, we'll look into it.

**Comment by Blazingfireflies** [comment]
this is common. after creating a character, it automatically tells you to create a world. just exit back to title and try to join again using the character you just created.

**Comment by Jofairden** [comment]
@Blazingfireflies doesn't that make this a vanilla issue then? Is this also happening for vanilla? If so, we should probably forward it to yoraiz0r instead.

**Comment by Jofairden** [comment]
Classified as a vanilla bug.

**Comment by JavidPack** [comment]
Wait...I'm pretty sure this doesn't happen in vanilla and we just missed a gotomenu item somewhere that we need to update.

**Comment by Jofairden** [comment]
Yorai said it was a known vanilla bug

Op 7 dec. 2017 03:22 schreef "JavidPack" <notifications@github.com>:
