### ISSUE TITLE
Failed to Resolve Assembly Error

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#267]
Under certain circumstances, mods fail to load properly. For some, ensuring that the tModLoader exe is named Terraria.exe fixes the problem, but it doesn't solve it for all users and is less than idea.

![](https://cdn.discordapp.com/attachments/103114194089431040/379970783105253379/image.png)

This bug is reliably reproducible if you delete all other exe files in the install folder and run a file named tModLoader.exe. Mods that can trigger the error include Calamity, ExampleMod, and AntiSocial. It is unclear what these mods share in common that provoke the error.

So far we have identified some code that helps:

	internal class TerrariaCecilAssemblyResolver : DefaultAssemblyResolver
	{
		public static readonly TerrariaCecilAssemblyResolver instance = new TerrariaCecilAssemblyResolver();

            public override AssemblyDefinition Resolve(AssemblyNameReference name, ReaderParameters parameters)
            {
                if (name.Name == "Terraria") {
                    if (parameters.AssemblyResolver == null) parameters.AssemblyResolver = this;
                    return ModuleDefinition.ReadModule(Assembly.GetExecutingAssembly().Location, parameters).Assembly;
                }

                return base.Resolve(name, parameters);
            }
       }

but the error also happens elsewhere in this code:

		static AssemblyManager() {
			AppDomain.CurrentDomain.AssemblyResolve += (sender, args) => {
				string name = new AssemblyName(args.Name).Name;

				if (name == "Terraria")
					return (Assembly.GetExecutingAssembly());

				Assembly a;
				loadedAssemblies.TryGetValue(name, out a);
				return a;
			};
		}

**Comment by JavidPack** [comment]
A note, this also caused dedicated hosts to error with the same problem. A fix there is to copy Terraria.exe to the server.

**Comment by Chicken-Bones** [comment]
Should be fixed by https://github.com/blushiemagic/tModLoader/commit/78edd7d7a7b0504b771bb7958f66cd1fc2649192
I was unable to replicate any issues with the AssemblyResolve callback (or even any instances of it being called) so I'll need separate replication instructions for that half of the bug
