### ISSUE TITLE
Mining tiles too fast doesn't set the "fail" flag in overriden KillTile (in GlobalTile)

### ISSUE THREAD

**Issue by NanobotZ** [blushiemagic/tModLoader#272]
### Description
I've noticed that mining tiles with one hit fast doesn't always set the "fail" flag in overriden KillTile from the GlobalTile class.
I've defined a new tile extending from GlobalTile and set up some debug texts:

```csharp
namespace MyMod{
	class MyModTile : GlobalTile {
		public override void KillTile(int i, int j, int type, ref bool fail, ref bool effectOnly, ref bool noItem) {
			Main.NewText("KillTile called..");
			if (fail) {
				Main.NewText(".. because of mining");
			}
		}
	}
}
```
and here's the result:
![3js8huq](https://user-images.githubusercontent.com/8195025/33089269-5c2730ee-cef0-11e7-8c9b-c0b21c7e5080.png)

### Steps to Reproduce
1. Extend a GlobalTile
2. Override KillTile method
3. Listen to the "fail" flag while mining with a fast and powerful pickaxe (compare copper pickaxe with shroomite digging claws).

### Expected behavior 
KillTile should always have a "fail" flag set when mined up in one hit too fast.
From summary: 
> Allows you to determine what happens when the tile at the given coordinates is killed or hit with a pickaxe. Fail determines whether the tile is mined, effectOnly makes it so that only dust is created, and noItem stops items from dropping.

### Actual behavior
KillTile doesn't always get a "fail" flag set when mined up in one hit too fast.

### Versions
tModLoader v0.10.1

### Mods
Only that one I'm trying to make right now.

**Comment by Jofairden** [comment]
I think you are just misunderstanding how the documentation is explaining the flag. The fail flag is used when some interaction happens with the tile (sound, dust, the cracks) but the tile isn't actually being destroyed. If you destroy the tile in one hit, I think it makes sense that the fail flag isn't triggered.

**Comment by NanobotZ** [comment]
Oh god, I've just now realized I'm dumb. I've not noticed that the name "fail" speaks for itself. Now I know that the flag is triggered only when tile is NOT mined. That's what happens when you're using your non native language and you're trying to think too fast...
Thank you for your response!

**Comment by Jofairden** [comment]
You're welcome.
