### ISSUE TITLE
Passcode errors

### ISSUE THREAD

**Issue by MacindowsRegistry** [blushiemagic/tModLoader#273]
### Description

Setting new passcode results in an error. While install TModLoader for the first time, no errors.

### Steps to Reproduce

1. Register on website
2. Generate pass code
3. Edit config -> Terraria -> Publish -> Error

### Expected behavior 

to login normally

### Actual behavior

Logging out and saying it's wrong

### Reproduction frequency

Infinite

### Versions

`v0.10.1 tModLoader`

### Mods

No mods related. Trying to publish mod, but error.

**Comment by JavidPack** [comment]
Did you manually edit the config file? If you did it that way, you'd have to restart terraria first. You should just paste into the game when prompted

**Comment by MacindowsRegistry** [comment]
Same error

**Comment by MacindowsRegistry** [comment]
![capture](https://user-images.githubusercontent.com/33797278/33148002-1276c74a-cf98-11e7-94c9-3cdb2c316929.PNG)

**Comment by MacindowsRegistry** [comment]
Is this anything?
![capture](https://user-images.githubusercontent.com/33797278/33148366-a25a0db2-cf99-11e7-9777-ce44f2935a59.PNG)

**Comment by JavidPack** [comment]
Not really. Come to the discord (discord.me/tModLoader) for help, this isn't really a tModLoader issue it looks like
