### ISSUE TITLE
NPC desync issue from seemingly normal spawns

### ISSUE THREAD

**Issue by hamstar0** [blushiemagic/tModLoader#275]
### Description
Got [a report](https://forums.terraria.org/index.php?threads/psycho.61219/page-2#post-1495371) of an npc sync issue via. my [mod in question](https://forums.terraria.org/index.php?threads/psycho.61219/), which uses [spawn rate adjustment](https://github.com/hamstar0/tml-psycho-mod/blob/master/MyNpc.cs) and [hp modify](https://github.com/hamstar0/tml-psycho-mod/blob/master/PsychoInfo.cs#L73) only (thus, desync in my code isn't likely).

He says this occurs after attacking a Psycho mob a few times. No word on whether other mobs have this problem.

### Steps to Reproduce
See post in question.

### Expected behavior 
See title/description.

### Actual behavior
Synced npcs.

### Reproduction frequency
Unknown to me.

### Versions
`v0.10.1 tModLoader`

### Mods
At *least* `Psycho v1.2.1.2` and `Hamstar Helpers v1.2.1`

**Comment by Jofairden** [comment]
Feel free to reopen the issue if you can provide a MCVE (Minimal, Complete, and Verifiable example)
