### ISSUE TITLE
Modified projectile knockback is ignored when hitting NPCs

### ISSUE THREAD

**Issue by Leemyy** [blushiemagic/tModLoader#278]
### Description

Modifying `knockback` in any of these hooks has no effect:
`ModProjectile.ModifyHitNPC`
`GlobalProjectile.ModifyHitNPC`
`ModNPC.ModifyHitByProjectile`
`GlobalNPC.ModifyHitByProjectile`
`ModPlayer.ModifyHitNPCWithProj`

### Steps to Reproduce

1. Have a `GlobalProjectile` that overrides `ModifyHitNPC`
2. In `ModifyHitNPC`, always set knockback to 0

### Expected behavior 

NPCs should no longer experience knockback from any projectiles.

### Actual behavior

NPCs are still knocked back by projectiles.

### Reproduction frequency

Always

### Versions

v0.10.1
v0.10.1.1

### Mods

None (Except a Test mod made to reproduce this issue)

### Additional Information

This is most definitely caused by a typo, as the calls to [`StrikeNPC`](https://github.com/blushiemagic/tModLoader/blob/ced3427843b1c2c6fb5745f3ac572022391f4124/patches/tModLoader/Terraria/Projectile.cs.patch#L272) and [`StrikeNPCNoInteraction`](https://github.com/blushiemagic/tModLoader/blob/ced3427843b1c2c6fb5745f3ac572022391f4124/patches/tModLoader/Terraria/Projectile.cs.patch#L277) in `Projectile.Damage` both use the instance variable `Projectile.knockBack`, instead of the local variable `knockback`.

**Comment by JavidPack** [comment]
Yep, seems to be a typo. Thanks, should be an easy enough fix.

**Comment by Jofairden** [comment]
It looks like there's 2 variables `knockback` and `knockBack` (this.knockBack, whereas knockback is local and adjustable), notice the capital letter. So yes, you are right.
