### ISSUE TITLE
setup.bat decompilation error (version mismatch)

### ISSUE THREAD

**Issue by MitchellMeier** [blushiemagic/tModLoader#280]
### Description

Trying to get tModLoader code for first time by following instructions on main git page.  When clicking setup button get Error: TerrariaServer version 1.3.5.3. Expected 1.3.5.1

### Steps to Reproduce

1. Follow instructions here https://github.com/blushiemagic/tModLoader#getting-the-tmodloader-code-for-the-first-time
2. Error appears after pressing setup

### Expected behavior 

No error

### Actual behavior

Error: TerrariaServer version 1.3.5.3. Expected 1.3.5.1

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Yes, tmodloader is based on 1.3.5.2 not 3, so you'll need to download an old version. 

See this, https://github.com/blushiemagic/tModLoader/issues/227#issuecomment-324450642
