### ISSUE TITLE
Item frame corrupts .tworld file upon putting a modded item on it.

### ISSUE THREAD

**Issue by ahllok** [blushiemagic/tModLoader#282]
### Description

World wont load after you put any modded item on an item frame (vanilla).

### Steps to Reproduce

1. Open terraria.
2. Load your world.
3. Get an item frame (vanilla item).
4. Get any modded item, i tested blood samples (from calamity) and glyphs (spirit).
5. Put the modded item on the item frame.
6. exit and save your world, load your world again.

### Expected behavior 

The world wont load anymore.

### Actual behavior

The world should load correctly.

### Reproduction frequency

2/2 times (all the time) 

### Versions

tModLoader v0.10.1.1

### Mods

BlockarozArmor
CalamityMod
chadsfurni
FKBossHealthBar
HEROsMod
ItemChecklist
MagicStorage
MoreAccessories
OreSeeds
RecipeBrowser
Shapeshifter
SpiritMod
TPUnchained
WikiSearch
Wildlife

### Additional Information

Related files will be attached to this report.
[Item frame bug report files.zip](https://github.com/blushiemagic/tModLoader/files/1566285/Item.frame.bug.report.files.zip)

**Comment by Jofairden** [comment]
Duplicate: #207

**Comment by ahllok** [comment]
Sorry, i should have checked more throughly on the open issues.
