### ISSUE TITLE
Suggestion: Support for texture atlases?

### ISSUE THREAD

**Issue by terorie** [blushiemagic/tModLoader#285]
### Summary
tModLoader could reduce loading times and raise FPS a lot by supporting texture atlases for Terraria. The rendering pipeline and shaders need to be rewritten and some algorithm for creating this atlas needs to be included.

### Hammering `glGenTextures`

Terraria currently seems to upload every single mod texture to the GPU separately.
This makes loading times extremely slow for tModLoader and has a rather big impact on performance.

To put things into perspective, I recorded all the OpenGL API calls with `apitrace`.
In the first ~**50 seconds** of loading some mods (e.g. Thorium Mod), Terraria and tModLoader generated **over 9000 OpenGL texture objects** (Not even a joke).

(GL calls recorded with `apitrace trace -a gl ./Terraria.bin.osx`, calls counted with `cat trace | grep glGenTextures | wc -l`)

GPUs simply aren't optimized for that kind of load.
But today they are so powerful these days that this waste of resources isn't even noticeable on most PCs.
Smaller laptops however should theoretically be running Terraria without problems, but are failing because of that exact reason.

[According to _mysticreddit_](https://www.reddit.com/r/Terraria/comments/6rrpzs/is_there_a_reason_all_of_terrarias_assetsgraphics/), this is a Terraria vanilla problem and tModLoader just makes it worse by introducing even more items.
*Can someone confirm that Terraria isn't using some caching or an atlas?*

I believe though, that tModLoader has the power to fix this by using texture atlases and rewriting the Terraria rendering pipeline.

### Texture atlases

Texture atlases could be used to group all these small textures into a big file. The shaders for all items, blocks etc. need to be rewritten and take the position (U,V) of the item in the atlas as arguments.

There are two ways to do this:

##### Compile-time batching
tModLoader creates an atlas for the Terraria items on installation and every mod introduces a new atlas with its items. When Terraria is run, only the atlases are loaded.

| PRO  | CON |
| ------------- | ------------- |
| Fixes a second issue: only 3-4 huge PNGs need to be loaded _from disk_ instead of thousands of little textures (Even faster loading times)  | Difficult to implement because an atlas needs to be generated for the vanilla files  |
| Existing texture packing algorithms can be easily used  | Novice modders will face a steeper learning curve because of the more complicated mod creating process  |

##### Run-time batching
When Terraria is started, read every texture PNG (like it is done now) and create a single huge atlas dynamically

| PRO  | CON |
| ------------- | ------------- |
| No files need to be changed and nothing needs to be generated on installation | Creating a texture atlas is slow and CPU intensive, there is a possibility that loading times are increased if implemented incorrectly (Why? Creating a 2D atlas with different texture sizes is an [NP-hard problem](https://en.wikipedia.org/wiki/Bin_packing_problem))  |
|                   | Reading thousands of little PNG files from disk is also slow. Run-time batching doesn't address that issue.  |

Both are rather hard to implement, Run-time batching is easier while compile-time is probably a lot faster and the way to go.

So maintainers of this mod, please consider this, Terraria texture code is so ugly and you have the power to fix it :)

**Comment by zauberparacelsus** [comment]
As a note, this problem is substantially worse under Mono/Linux.  On .Net/Windows, loading times are anywhere from five to ten times faster.

**Comment by terorie** [comment]
Yep, also on macOS. It takes about 3 minutes to load the Thorium mod because of the shitty Intel iGPUs.

**Comment by glehu** [comment]
Nice work terorie

**Comment by Pop000100** [comment]
i think run time batching is the only one that supports texture packs though with out making  a special case for them.

**Comment by Jofairden** [comment]
Seems like a rather big undertaking to implement, as wel as modders to adapt to. We  considered letting tML generate the atlas (I think?), but that would probably be pretty expensive.

**Comment by terorie** [comment]
@Jofairden yeah generating an atlas while loading is what I meant with Run-Time batching.
I forgot to mention, we could cache the results from Run-Time batching and also get all the benefits from Compile-Time batching!

That is, fast loading times and efficient GPU usage.
The only downside would be that Terraria used more space.

What would make batching really fast is only doing texture atlasing by grouping items with the same size first.
All blocks and walls would get in one texture, special vanity blocks and crafting stations (2x3, 3x3, …) have their own textures. You can do that in `O(n)` time, so no problem.

**Comment by Chicken-Bones** [comment]
Batching is a fine idea, though we'd need to do more detailed analysis of the gl call stack for a single frame to really determine hotspots. The difficulty in implementing it thus far isn't generating an atlas, it's replacing every call to SpriteBatch.Draw, which we couldn't really do unless we started transforming Terraria at runtime using Mono.Cecil (which is definitely possible, we're just not sure we want to commit to this path yet)

**Comment by Chicken-Bones** [comment]
Closing this as mostly infeasible in a modded environment. There are too many edge cases to consider.
