### ISSUE TITLE
side = NoSync gets stuck on syncing mods when enabled on server and disabled on client

### ISSUE THREAD

**Issue by Luiafk** [blushiemagic/tModLoader#287]
### Description

When you have `side = NoSync` in `Build.txt` you will get stuck on syncing mods if the mod is enabled on the server but not on the client.

### Steps to Reproduce

1. Create new mod with empty Mod class.
2. Add `side = NoSync` in `Build.txt`
3. Enable mod on server and start world.
4. Disable mod on client and try to enter server.

### Expected behavior 

It should connect.

### Actual behavior

It gets stuck on syncing mods.

### Reproduction frequency

All the time.

### Versions

Latest (0.10.1.1).

### Mods

Only the empty mod with `side = NoSync`

### Additional Information

  @Chicken-Bones 
See comment in below code.
`ModNet.cs`
```
internal static bool HijackGetData(ref byte messageType, ref BinaryReader reader, int playerNumber)
{
	if (netMods == null)
	{
		return false;
	}

	bool hijacked = false;
	long readerPos = reader.BaseStream.Position;
	long biggestReaderPos = readerPos;
	foreach (var mod in netMods)
	{
                //constantly throws nullreferenceexception on this if because mod == null
		if (mod.HijackGetData(ref messageType, ref reader, playerNumber))
		{
			hijacked = true;
			biggestReaderPos = Math.Max(reader.BaseStream.Position, biggestReaderPos);
		}
		reader.BaseStream.Position = readerPos;
	}
	if (hijacked)
	{
		reader.BaseStream.Position = biggestReaderPos;
	}
	return hijacked;
}

**Comment by Luiafk** [comment]
Oh, and on a related note, is there any way for a client to find out if a `NoSync` mod is enabled on the server as well other than using reflection to check `mod.netID`?

If that's the only way to check could `netID` have a public getter or something?

**Comment by Chicken-Bones** [comment]
I'll have to followup on this. I believe the intent was for the client (or server) mod to send a packet, and the other side would reply if it was there

**Comment by Luiafk** [comment]
Oh, in that case I should probably add that trying to send a packet when the mod is only enabled on the client throws an exception when calling GetPacket because there's no mod on the other side.

**Comment by Chicken-Bones** [comment]
Try https://github.com/blushiemagic/tModLoader/commit/9a434101cbc3d09329b39d10e8a1ac385005ed88
