### ISSUE TITLE
Calamitymod /

### ISSUE THREAD

**Issue by ajablonowski** [blushiemagic/tModLoader#288]
### Description
tmodloader fails to load Calamitymod

### Steps to Reproduce

load & install tmod loader, then use it to install calamitymod

### Expected behavior 
should allow use of calamitymod

### Actual behavior
error and fails to load

### Reproduction frequency
consistent failure to load on desktop PC

### Versions
v1.3.5.2, tModLoaderV0.10.1.1

The tModLoader version should be notified in the bottom left corner when in the main menu. Follow this format: `vX.X.X.X tModLoader` or `tModLoader vX.X.X.X`

### Mods
CalamityMod

### Additional Information
system runs Win7 SP1, 64-bit, 4GB RAM, not sure on GPU
error & log pasted below:
The wav sound file at Sounds/Item/FlareSound.wav failed to load
   at Terraria.ModLoader.Mod.Autoload()
   at Terraria.ModLoader.ModLoader.do_Load(Object threadContext)

Inner Exception:
External component has thrown an exception.
   at Microsoft.Xna.Framework.Audio.SoundEffect.AllocateFormatAndData(Byte[] format, Byte[] data, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Audio.SoundEffect..ctor(Stream stream)
   at Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(Stream stream)
   at Terraria.ModLoader.Mod.Autoload()

![image](https://user-images.githubusercontent.com/35087707/34548771-dfab4772-f0d1-11e7-879c-5999bd2d6191.png)

**Comment by zauberparacelsus** [comment]
This is probably something you should be reporting to CalamityMod's author.

**Comment by ajablonowski** [comment]
thanks, done that as well.  Continuing, the game crashes - error log pasted below:

Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at Terraria.GameInput.TriggersSet.Clone()
   at Terraria.GameInput.PlayerInput.UpdateInput()
   at Terraria.Main.DoUpdate_HandleInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)

**Comment by Jofairden** [comment]
This is an ongoing issue with no further investigation, FlareSound.wav pops up everytime and the user always has 4GB ram. That amount of RAM is really low, and people tend to suffer from loading issues with big mods, and unfortunately there isn't really a fix. You can ask the devs to put the sound file in a different smaller format, such as mp3, as the conversion may work rather than loading the entire wav. If this doesn't work, or they don't do it, this will be a hard one for the user. We do not know why the AllocateFormatAndData error shows up, initially I thought of corrupted wavs but they do not seem to be an issue. Now I think it's a streaming issue in the code, but it remains to be found if it exists.

**Comment by ajablonowski** [comment]
thanks - appreciate the response
    On Wednesday, January 10, 2018, 6:52:02 PM EST, Jofairden <notifications@github.com> wrote:  
 
 
This is an ongoing issue with no further investigation, FlareSound.wav pops up everytime and the user always has 4GB ram. That amount of RAM is really low, and people tend to suffer from loading issues with big mods, and unfortunately there isn't really a fix. You can ask the devs to put the sound file in a different smaller format, such as mp3, as the conversion may work rather than loading the entire wav. If this doesn't work, or they don't do it, this will be a hard one for the user. We do not know why the AllocateFormatAndData error shows up, initially I thought of corrupted wavs but they do not seem to be an issue. Now I think it's a streaming issue in the code, but it remains to be found if it exists.

**Comment by JavidPack** [comment]
For those with the sound loading errors, some have reported that enabling Windows Audio Service or plugging in headphones helps. I'm not positive, but I suspect this error is likely related to Sound loading simply crashing on machines with no speakers available.

**Comment by Xetaxheb** [comment]
Regardless of other issues, you should not be installing calamity through mod browser. Get the latest version off the discord https://discord.gg/29ccBym or the forum thread https://forums.terraria.org/index.php?threads/calamity-mod.44065/

@ajablonowski

**Comment by JavidPack** [comment]
See #308
