### ISSUE TITLE
ModPalmTree growth issue

### ISSUE THREAD

**Issue by Jenosis** [blushiemagic/tModLoader#289]
### Description

Modded Palm Trees aren't growing in multiplayer or singleplayer

### Steps to Reproduce

1.plant sapling on the modpalmtrees' block
2. wait

### Expected behavior 

It's supposed to grow in both SP and MP like modtrees and cactuses do
### Actual behavior

mod palm sapling isn't growing into the modded palm tree

### Reproduction frequency

always

### Versions

v0.10.1.1

### Mods

Furniture, Food, and Fun

**Comment by Jofairden** [comment]
I think this was known before, interesting if it wasn't fixed.. Maybe we just forgot

**Comment by JavidPack** [comment]
That was the incorrect drawing. This is separate.

**Comment by blushiemagic** [comment]
Confirmed to be a modder error
