### ISSUE TITLE
Country-wide imgur blocks break Mod Browser

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#290]
From: https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/page-954#post-1523300

![](http://i68.tinypic.com/zvofp1.png)

> From what I gather, the gist of it is this; I live in Turkey. Imgur is blocked in Turkey. When the Mod Browser tries to load up mod thumbnails, if those thumbnails are Imgur images, it will screw up. Could we have a setting that disables thumbnails in the Browser?

(This is not just Turkey, btw. It was reported for some other countries.)

To fix this, I guess we need to add some error handling to the thumbnail downloading code and not assume we will get a valid image back.

**Comment by Jofairden** [comment]
Should we replace images with a default placeholder or omit them entirely?

**Comment by Chicken-Bones** [comment]
The browser should host the images

**Comment by Jofairden** [comment]
@Chicken-Bones I agree, but it could be a while before we see to that solution.

**Comment by Jofairden** [comment]
I made a subpar solution for this, but we could roll with it unless we want to invest more time into it. A block can be tested by putting these in your hosts file:
```
127.0.0.1 imgur.com
127.0.0.1 imgur-d.openx.net
127.0.0.1 s.imgur.com
127.0.0.1 m.imgur.com
127.0.0.1 i.imgur.com
127.0.0.1 store.imgur.com
127.0.0.1 p.imgur.com
127.0.0.1 apidocs.imgur.com
127.0.0.1 blog.imgur.com
127.0.0.1 help.imgur.com
127.0.0.1 browserevents.imgur.com
127.0.0.1 imgurads.com
```
For now, it will catch exceptions thrown when trying to download the image. If it does, the image is simply not loaded and positions are reset. Feel free to reopen this issue guys.
