### ISSUE TITLE
Buying items sold to a NPC reduces their value

### ISSUE THREAD

**Issue by DarkLight66** [blushiemagic/tModLoader#292]
### Description

Selling an item to a NPC then buying it back reduces its value as if the item was one of the items the NPC sells normally. Doing this over and over reduces the value until it becomes 1.

### Steps to Reproduce

1. Sell any item to a NPC
2. Buy the item back

### Expected behavior 

The item's value is the same as it was before being sold

### Actual behavior

The item's value is 1/5 the value the item had before being sold

### Reproduction frequency

Always

### Versions

tModLoader v0.10.1.1

### Mods

None

**Comment by Jofairden** [comment]
Non persistent bug: if you close and re-enter the world values are back to normal.

**Comment by Jofairden** [comment]
Actually poor fix, noticed by another dev.
