### ISSUE TITLE
Bugs with ModPrefixes

### ISSUE THREAD

**Issue by DarkLight66** [blushiemagic/tModLoader#297]
### Description

* The category of a ModPrefix cannot be set without using reflection (although it defaults to Custom).
* ModPrefix.GetPrefixesInCategory() doesn't seem to work as intended, as it always returns an empty list regardless of parameters (although only the Custom category should have any prefixes on it, due to the previous problem).
* ItemLoader.ChosePrefix() gets called without checking if the item's max stack is 1 (i'm not sure if this is intended).

### Versions

tModLoader v0.10.1.2

**Comment by Jofairden** [comment]
What do you mean you can't set the category? Just set the Category property in SetDefaults. GetPrefixesInCategory works perfectly fine. ChoosePrefix() doesn't need to handle stack because the calling code already does. (vanilla assumes something being prefixed doesn't have a stack)

**Comment by DarkLight66** [comment]
The Category property has `internal set`, so it cannot be changed by mods.
I assumed ChoosePrefix() needed a check for max stack since GeneralPrefix() checks for that too, good to know it doesn't (sorry, i should have tested that).

**Comment by Jofairden** [comment]
Ah, I see that indeed it's on internal. I will fix it immediately.

Basically, in vanilla you only prefix weapons. Vanilla assumes a weapon isn't stackable, so in many places there aren't really checks for that.

**Comment by DarkLight66** [comment]
What about `ModPrefix.GetPrefixesInCategory(PrefixCategory category)` ? It always returns an empty list, no matter how many ModPrefixes are added, even for PrefixCategory.Custom, which is the only one that can be added to right now.
