### ISSUE TITLE
The mod browser server is under heavy load please try again.. 

### ISSUE THREAD

**Issue by NacGod** [blushiemagic/tModLoader#30]
For some reason, Everytime I try to download a mod it says The mod browser server is under heavy load please try again.. Please fix this its very annoying

**Comment by bluemagic123** [comment]
It's not a bug, it's because it's under heavy load. In the meantime, you can try to download mods from their homepages.

**Comment by Chicken-Bones** [comment]
Consider leaving this open both as a reminder until we get a better server, and as reference for future people tempted to post the same issue?

**Comment by bluemagic123** [comment]
That sounds like a good idea.

**Comment by JavidPack** [comment]
Close for now.
