### ISSUE TITLE
dllReferences load issues

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#305]
dllReferences have load issues. They can be present in the dllReferences folder, but will not load properly (thus failing builds) unless placed in ModCompile/ as well. I suspect it has to do with changes to the roselyn wrapper.

Same thing happens for `System.Collections.Immutable.dll` and others btw (no dllref)

I'll leave a test dll for dllref:
System.Numerics: `https://cdn.discordapp.com/attachments/103115427491610624/417415398313558027/System.Numerics.dll`
System.Collections.Immutable: `https://cdn.discordapp.com/attachments/103115427491610624/352120158439079936/System.Collections.Immutable.dll`

**Comment by PurplefinNeptuna** [comment]
Are you talking about mod's dllreferences?
it's happen to me too, but strangely, if i put my .dll at `lib/` folder and list it in `dllReferences = ` at `built.txt` it works perfectly

**Comment by Jofairden** [comment]
Yeah, strangely it does. It's a weird thing. I remember dllReferences folder being a thing (a folder in /ModLoader/ that you put the dlls in for mods), but I cannot find any commit that worked on that. So maybe the documentation was always wrong and my memory fails me...

**Comment by PurplefinNeptuna** [comment]
what are you going to do with that, leaving dll references in lib or not? because there are some mods work with external dlls

**Comment by Jofairden** [comment]
Closing. Odd issue, and it probably bad remembrance. If someone is having this issue, make sure to put your references in the `lib/` folder, inside your mod source.
