### ISSUE TITLE
Automated player and world backups

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#306]
## Intro
A modder or user might want automatic backups by tModLoader of player and world files. Not out of necessity, but usefulness. A corrupt mod maker could easily perm. erase a user's files, possibly deleting their life work. Suggestion opened for debate with this issue thread.

## Suggested
By default, feature is toggled off, as it sort of spams personal storage.
Feature is toggable through settings, and has a few modes:

- On launch backup
    - Creates a backup only everytime the exe is started
- On exit backup
    - Creates a backup only on exit of exe (harder! how to detect forced termination?)
- On interval backup
    - Creates a backup every set interval, timed between minutes, hours, days or weeks.

Or, instead of modes, any or more toggable (multiple modes at the same time)
____
Suggested method of storage is folders by epoch time and/or just date (at the time of performing the backup), which contains the backups, along with a file that has information about installed and enables mods during the backup. Location: `ModLoader/Backups/Players` / `ModLoader/Backups/Worlds` 

Other suggested feature is automated deletion of backups older than # time.

**Comment by whismerhill** [comment]
In my humble opinion, this feature should be associated to when/if worlds can be associated with modlists

reason : that means you can limit backups to say : when a modlist has been changed and only for the affected worlds, and then the world gets a flag which means any player joining that world gets a backup before entering ?

why ? because it would limit the "spamming" of savegames & backups

it's just my opinion though.

**Comment by JavidPack** [comment]
I think it would be more worth our time tracking down the bug that causes both the world and the backup to be erased/filled with zeros. I think it has to do with exceptions happening during ModWorld.Save, but I haven't been able to track it down yet. In any case, something is up when both the backup and normal .wld files get corrupted at the same time.

**Comment by Jofairden** [comment]
We totally need to track that down. In any case, extended backup system is still great to make. We're still dealing with modded. No matter what we fix now, new problems will arise _eventually_. It's not a matter of if, but when.

@whismerhill Certainly interesting. Could be a 'on mod(s) change' toggle.

**Comment by Chicken-Bones** [comment]
I'm going to vote for this issue, I implemented something similar with the logging system, and it would be very good for recovering worlds/players.

The average world size is 11-12MB, zipped to around 4.5MB
I suggest the following:
New folders Players/Backups, Worlds/Backups
Track down anything that's killing .bak files
Each time a world is successfully loaded, make a daily backup if there has not already been one made today
Go through the backups for this world from oldest to newest:
  set the timeframe for that backup to month|week|day based on floor(timesincebackup)
  if there is an older backup within that time-frame, delete the older one.

This will keep one backup per day for the last week, one per week for the last month, and one per month for all time

Add a backup size limit (say 200MB by default) after which backups are always deleted, oldest first.

**Comment by Jofairden** [comment]
That sounds pretty solid, I'm up for this.
