### ISSUE TITLE
UICycleImage as public ?

### ISSUE THREAD

**Issue by whismerhill** [blushiemagic/tModLoader#307]
### Description
would it be possible/interesting to expose UICycleImage so we modders can reuse it instead of recoding it or copy/pasting the code in our project?

### Steps to Reproduce
insert the following CS code in a separate mod project from tmodloader : 
```Csharp
using System.Collections.Generic;
using Microsoft.Xna.Framework.Graphics;
using Terraria;
using Terraria.UI;
using Terraria.ModLoader.UI;
using System.Reflection;
using System.Linq;

namespace something
{
    public class Test
    {
        public UICycleImage TestCycleToggle;
    }
}
```

### Expected behavior 
UICycleImage is accessible for outside mods

### Actual behavior
Visual Community shows an error : 
Error	CS0122	'UICycleImage' is inaccessible due to its protection level

### Versions
 `v0.10.1.2 tModLoader` 

### Additional Information
I believe it's because UICycleImage is declared as internal in tmodloader source code ?
line 8 : https://github.com/blushiemagic/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader.UI/UICycleImage.cs

I hope there's enough information, tell me if not.

**Comment by Jofairden** [comment]
I think @jopojelly made the entire thing (according to the blame), so let's have him decide.

**Comment by JavidPack** [comment]
It's a fairly simple and limited UIElement. I'm fine with it being public, but I'll probably want to make it more useful with an OnStateChanged event first, at the very least. 

I'll try to do this soon.

**Comment by whismerhill** [comment]
thanks @JavidPack
