### ISSUE TITLE
Extract Mod extracts .png images to .rawimg

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#310]
The image loading improvements of 0.10.1.2 have resulted in the extract mod function outputting what were initially .png files as .rawimg files. 

We can either leave this as it is, or convert them back to png files. 

Converting back to png files might lead to different filesizes or artifacts. (I'm not sure.)

This is just here so we can either discuss or just make modders aware of this behavior.

**Comment by Jofairden** [comment]
Preferably convert back to png.

**Comment by Tyfyter** [comment]
Anyone, including image conversion sites.
