### ISSUE TITLE
Modded multiplayer slow motion

### ISSUE THREAD

**Issue by UpriseDragon** [blushiemagic/tModLoader#312]
Hello all... Im having troubles playing multiplayer with my brother on tmodloader, when i host all goes fine with friends but my brother goes slow motion at about 10 max 15 fps (in single player he runs the game fine and smoothly), we tried everything like changing the game priority, hosting with the console and host and play(deleting all mods too) but nothing works. What should we do? thanks in advance.

**Comment by Chicken-Bones** [comment]
What happens when he hosts?

**Comment by Jofairden** [comment]
No further information was given and a duplicate (?) issue was made for this (#321)
Use the image I provided in #321
