### ISSUE TITLE
Unable to join multiplayer session [Linux to Windows]

### ISSUE THREAD

**Issue by kennethdhau** [blushiemagic/tModLoader#313]
### Description

Unable to join a multiplayer session (tested with Client Linux, Server Windows)

### Steps to Reproduce
1. Attempt to join (by IP or by Steam)

### Expected behavior 

Expected to join game

### Actual behavior

Finds server, clears unused resources (if re-attempting), and retrieves data to 100%. Then stalls. _Cancel_ button functions and permits reattempts.

### Reproduction frequency
100% reproduction rate.

### Versions
0.10.1.3

The tModLoader version should be notified in the bottom left corner when in the main menu. Follow this format: `vX.X.X.X tModLoader` or `tModLoader vX.X.X.X`

### Mods

Thorium
Helpful Hotkeys
imksushi
Reduced Grinding
Magic Storage

### Additional Information

No access to attempt reproduction in other direction ( sorry :( ). Both machines using same version of tModLoader.

Linux environment:
Arch 4.15.6-1 x86_64
Nvidia driver: 390.25-14 with bumblebee 3.2.1-16
Discrete graphics: Nvidia M2000M

Windows environment:
Windows 10 x86_64
Nvidia GTX 1080

**Comment by JavidPack** [comment]
We can't really do anything unless you test with 0 mods. If you can connect with 0 mods, then use the process of elimination to figure out which mod is breaking.

**Comment by kylep84** [comment]
I also use arch and had issues running a tmodloader server, turns out it was related to arch using a newer ncurses library. Try setting setting the TERM env variable to xterm then re-launch. That allowed me to run my tmodloader server on arch.

**Comment by PoroCYon** [comment]
That's an unrelated mono issue.

**Comment by kennethdhau** [comment]
@kylep84 this is from the graphical interface
@JavidPack I hope to be testing this on Linux-Linux and Linux-Windows with and without mods this weekend

**Comment by kennethdhau** [comment]
I got a Linux-Windows connection to work. I wasn't able to track down a cause, but it may have been an out-of-date plugin or some misconfiguration on my end.
