### ISSUE TITLE
Hash mismatch, data blob has been modified or corrupted?

### ISSUE THREAD

**Issue by AMassiveWeeb** [blushiemagic/tModLoader#315]
### Description

Every time i try to run Terraria with the latest version of TModLoader, i get this error message as soon as Terraria opens:

Hash mismatch, data blob has been modified or corrupted
   at Terraria.ModLoader.IO.TmodFile.Read(LoadedState desiredState, ReadStreamingAsset streamingHandler)
   at Terraria.ModLoader.ModLoader.FindMods()

I have no clue what to about this. I even tried installing it using the java installer, and it still did the same thing. I feel like I'm making a really stupid mistake, but I can't find out where I'm going wrong, that would be great

### Steps to Reproduce
1. Install tModLoader
2. Launch Game

### Expected behavior 

I expect the game and the mod loader to run as intended

### Actual behavior

i get the error message shown above, and I can't look at my mods or the mod browser

### Reproduction frequency

every single time

### Versions

tModLoader v0.10.1.3

### Mods

1               Alternate Swapper 
2               Auto Trash 
3               Calamity Addon 
4               Calamity Mod 
5               Crystilium 
6               Celestial Mod 
7               MoreAccesories+ 
8               More Chest Loot 
9               No More Tombs 
10              NPC Info 
11              Recipe Browser 
12              Reduced Grinding 
13              RPG Classes 
14              The Shapeshifter 
15              Shorter Respawn Time 
16              Spirit Mod 
17              Succubi's Wrath 
18              Thorium Mod 
19              Tremor Mod Remastered
20              Unleveled Mod

(Yes I have tried with the mods disabled)

### Additional Information

This only started when I installed the newest version of tModLoader. This didn't happen on older versions.

**Comment by Chicken-Bones** [comment]
We didn't actually test how tML handles corrupted mod files, we should do that. 

For you, right now, copy all your mods to a different folder (or rename your Mods folder to ModsOld) or something and then add them back one by one

**Comment by AMassiveWeeb** [comment]
sure, i'll try that. Thanks a lot

**Comment by JavidPack** [comment]
To add to this issue, as something else we need to test, having a 0.6 mod in the Mods folder also crashes:

![](https://i.imgur.com/wUHSD7I.jpg)

**Comment by Chicken-Bones** [comment]
I believe read errors are handled properly now. Logged and not shown in mods list.
