### ISSUE TITLE
Modded multiplayer issues

### ISSUE THREAD

**Issue by UpriseDragon** [blushiemagic/tModLoader#321]
Hello all... Im having troubles playing multiplayer with my brother on tmodloader, when i host all goes fine with friends but my brother goes slow motion at about 25-30 fps with frame skip off and subtle and lags with frame skip on  (in single player he runs the game fine and smoothly), we tried everything like changing the game priority, hosting with the console and host and play but nothing works. What should we do? thanks in advance.

**Comment by Jofairden** [comment]
For one, you should state your modlist. I am closing this because it is an issue in one of the mods you are playing, not tModLoader. See:
![](https://camo.githubusercontent.com/1a5305a45654b6d834242da3f1b6ee5f6083a66f/687474703a2f2f692e696d6775722e636f6d2f356e47503651692e706e67)
