### ISSUE TITLE
GetX by type in static context is decentralized

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#322]
## Issue
Getting X modded thing is decentralized. You can get something by type, however, not everything is in the same class. For example ModBuff has BuffLoader and you use BuffLoader.GetBuff, but ModDust does not have DustLoader and you use ModDust.GetDust

## Suggested solution
Discussed solution is implementing GetX on ModX class (i.e. ModBuff.GetBuff, ModDust.GetDust, ModItem.GetItem ...) which forwards to loaders or the appropiate class.

**Comment by Chicken-Bones** [comment]
Should be `ModX.GetModX`

**Comment by Jofairden** [comment]
We need to be clear on the naming, what do we prefer? 'Mod' is already specified by the ModX class, but doing a GetBuff would return a ModBuff not a Buff so it may be unclear. Just a Get seems too short / lacks information. What about `ModX.GetByType`? (e.g. `ModBuff.GetByType(type)`) That however, doesn't really follow the convention applied in Mod (GetX)

**Comment by Chicken-Bones** [comment]
I will also accept `ModX.GetById` or `ModX.FromType`

**Comment by Jofairden** [comment]
In the current implementation, loaders follow the format of `XLoader.GetX` not `GetModX`. 
`ById` is weird since it's always called `type`.
If we change the naming convention, it may be confusing to modders. 
I suggest we'd stick with `ModX.GetX` or `ModX.GetModX`

**Comment by Jofairden** [comment]
Great for solving this. It's a nice improvement
