### ISSUE TITLE
API restructuring megathread

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#323]
This thread serves the purpose of discussing and keeping track of the restructuring of the API that will be happening this summer. Over time certain things have gotten 'messy', in ways that could sometimes see large or small improvements. This thread will be locked to contributors only.

- [x] ModContent
  - [x] 1) All loading and unloading code facilitated by its predecessor, as well as ResizeArrays, GetTexture.
  - [x] 2) Manage mod hotkeys/music/sounds/language methods
- [x] ModOrganiser
  - [x] 1) Handle sorting (modsDirCache, FindMods, LoadMods) and mods' dependencies
  - [x] 2) do_Load renamed to LoadMods, Load to LoadAsync. LoadMods calls MorOrganiser.LoadInstances and ModContent.LoadContent 

Each improvement made should be part of its own branch were sometimes multiple improvements may be conjoined if they have shared benefits, after which they become subject to review via a pull request.

Appendix:
**ModLoader** should manage /mods/

**ModContent** should manage content added by mods, the loading, unloading and integration of such.
This is responsible for the second half of loading, ResizeArrays UnloadContent GetTexture and anything else that doesn't have a home, the liaison between mod content and Terraria's arrays. It should oversee the Loader classes

**ModOrganiser should manage the sorting and dependencies of mods**
Responsible for everything up to acquiring an actual Mod instance, except what's covered by AssemblyManager
This includes searching the mods directory, updating the internal list of LocalMod which mirrors the contents here, enabling and disabling mods, verifying dependencies and target versions, and sorting a set of mods to load.

**Comment by Jofairden** [comment]
Locking to restrict discussion to collaborators for now.

**Comment by Chicken-Bones** [comment]
Modloader.cs is a mess
1. `loadOrder` should be removed, `loadedMods` is already sorted
2. `GetLoadedMods` should be removed, `LoadedMods` is fine
3. the sorting functions, `modsDirCache`, `FindMods`, and current `LoadMods` function should be moved to a `ModOrganiser` class
4. all content stuff (`Autoload`, `ResizeArrays` etc) to a `ModContent` class
5. `do_Load` should be renamed to `LoadMods`, `Load` to `LoadAsync` `LoadMods` should just be `ModOrganiser.LoadInstances` and `ModContent.LoadContent`
6. The current Mod class is pretty good, but all autoloading should be moved to either `ModContent` or `ModAutoloading` depending on the new size of `ModContent`

The `XLoader` naming convention and pattern is fine.

Localisation needs a solid review

**Comment by Chicken-Bones** [comment]
`ModItem.projOnSwing` and `ModItem.bossBagNPC` should be changed to get only properties. Having a few isolated fields that most ModItems won't use, having to be cloned etc. They should both be virtual properties (or even no-arg methods) because they're really hooks

**Comment by Jofairden** [comment]
> 6.1 Autoloading could also be split among the individual Loader classes, but I'm not quite as sure on this, I think a central place is good

The problem with this is that the loading code tends to get quite big. Right now the bulk of Mod.cs is loading code. All we'd be doing is moving that bulk of code to a new class. As we add more stuff (which we will inevitably) that new class becomes just as problematic as it is now for Mod.cs In my opinion we should abstract how something is loaded to its own class _or_ its loader, so that we aren't just moving the problem to a new class but actually addressing it.

**Comment by Chicken-Bones** [comment]
ModOrganiser
  Responsible for everything up to acquiring an actual `Mod` instance, except what's covered by `AssemblyManager`
  This includes searching the mods directory, updating the internal list of `LocalMod` which mirrors the contents here, enabling and disabling mods, verifying dependencies and target versions, and sorting a set of mods to load. 
  It then hands off a `List<LocalMod>` to `AssemblyManager.InstantiateMods` and recieves and stores the `mod list`, `ModLoader.LoadedMods` would point here

ModContent
  This is responsible for the second half of loading, `ResizeArrays` `UnloadContent` `GetTexture` and anything else that doesn't have a home, the liason between mod content and Terraria's arrays. It should oversee the Loader classes

The problem with autoloading isn't that the class gets quite big, it's that the current location crowds out the rest of the class's functionality. A dedicated class to autoloading is a good solution. In my opinion, because all the autoloading code is very similar, I think it's better to put it all in one class, (just like how Mod.AddX is all in one class) rather than putting a large chunk of Autoloading in each of the various things that can be autoloaded (especially because some things don't have a dedicated Loader class [and shouldn't need one])

**Comment by Jofairden** [comment]
> The problem with autoloading isn't that the class gets quite big, it's that the current location crowds out the rest of the class's functionality. A dedicated class to autoloading is a good solution. In my opinion, because all the autoloading code is very similar, I think it's better to put it all in one class, (just like how Mod.AddX is all in one class) rather than putting a large chunk of Autoloading in each of the various things that can be autoloaded (especially because some things don't have a dedicated Loader class [and shouldn't need one])

Maybe you're right. I also didn't consider some code can possibly be refactored/shortened.

The 2 classes sound good 👍

**Comment by Jofairden** [comment]
Initial work started.
5a1bf033f6b608bdd757a8bc1d0d55539fc6fba6

Created ModOrganiser and ModContent classes
Right now it is likely ModOrganiser is implemented slightly wrong, and needs adjusting in the future.
For now at least some initial work is done, the client builds and mods load however mods break due to migration to the ModContent class (almost all content mods use .GetTexture() etc.) so everyone will need to make their own test mods.

Aside from migrating code no real refactoring has been done in this commit.

**Comment by Jofairden** [comment]
d0d9389 
ModOrganiser now clearly manages mod 'organisation'
ModContent manages mods' content
ModLoader is still in charge of mods, mods contain both organisation and content
ModLoader still needs forwarder methods (for example GetTexture())
loadOrder stack is marked for deletion as it may be unnecessary if the mods are already in load order
No real refactoring was done yet at this time
ModOrganiser.IsEnabled renamed to IsModEnabled for clarity

**Comment by Chicken-Bones** [comment]
94e1c869d5b14f051b6d5d9d087ee575d067290d
839300bf4d427f75dd4a925d98ed21571a3454e6
1008294e918e81ba50c494209c34cf4db717cb72
81ef29532e4c9dc588add36264ac70424d7d715f
404d5695e20aef57e9e496e376e7b68bb8d263aa
e6f7a8714df86a98fb37f3fd6b2a9e8e80ebd74c

Refactoring performed. Thanks @Jofairden for the sketch on your api rework branch. Can be deleted now
