### ISSUE TITLE
Allow mod building on linux/mac

### ISSUE THREAD

**Issue by toshnika** [blushiemagic/tModLoader#333]
I'm a linux user who really wants to make mods. Any attempt to build a mod briefly says compiling mod for windows, followed immediately by a crash.

**Comment by JavidPack** [comment]
For now, this is how mods are built on linux/mac: https://forums.terraria.org/index.php?threads/.23726/page-525#post-1001200

**Comment by Chicken-Bones** [comment]
That post needs to be updated to mention Rider

**Comment by Jofairden** [comment]
I will update the docs some time to include more editors / environments (np++, rider, VS, windows/linux etc.)

**Comment by Chicken-Bones** [comment]
I notice we do have a link that points to that post in our wiki. Can we just bring it into the wiki here instead?

**Comment by JavidPack** [comment]
We have permission to migrate the guide to the wiki from the original author, but I haven't gotten around to doing it yet.

**Comment by Jofairden** [comment]
I probably have time to do it on friday.

**Comment by Jofairden** [comment]
Considering the migration of the guide has started, I will go ahead and close this issue for now. The guide can be found [here](https://github.com/blushiemagic/tModLoader/wiki/Developing-on-Mac-or-Linux)
