### ISSUE TITLE
cross platform deficiency? make sure you have exactly one class extending mod

### ISSUE THREAD

**Issue by toshnika** [blushiemagic/tModLoader#334]
So, I compiled my mod with mono develop, and whenever I click build (in mod sources), it outputs the error "make sure you have exactly one class extending mod" I have deleted all content and the problem still persists.

**Comment by JavidPack** [comment]
This is a troubleshooting problem, not a bug, come to discord to chat. It might be build.txt not having noCompile set or some other issue.

**Comment by toshnika** [comment]
I've been locked out of my discord account
