### ISSUE TITLE
Request for mana uncap hook/tml change

### ISSUE THREAD

**Issue by SirAzazel** [blushiemagic/tModLoader#338]
By default Terraria same as tModLoader has maximum mana limit of 400 which i believe cannot be changed on the mod's end. 
I remember either tAPI or tConfig had such feature present in them and i believe such feature would be helpful to modmakers for tModLoader that make RPG mods or just mods that overhaul base gameplay.

**Comment by basdxz** [comment]
We're sorry to inform you that your issue cannot be resolved at this time, please enjoy this recipe for chocolate cake instead.

Ingredients

    For the chocolate cake:
    3 large eggs
    175g (6 oz) self-raising flour
    175g (6 oz)caster sugar
    175g (6 oz) softened butter
    1½ level tsp baking powder
    40g (1½ oz) cocoa powder
    4 tbsp boiling water
    A little icing sugar, to serve
    For the chocolate spreading/ganache icing:
    150ml (5fl oz) double cream
    150g (5oz) plain chocolate, broken into pieces
    4 tbsp apricot jam
    To make Mary Berry's chocolate cake recipe you will also need:
    2 x 17cm (7 in) deep sandwich tins, greased and lined with non-stick baking paper


Method

    Preheat the oven to 180C, gas 4.

    Beat together the eggs, flour, caster sugar, butter and baking powder until smooth in a large mixing bowl.

    Put the cocoa in separate mixing bowl, and add the water a little at a time to make a stiff paste. Add to the cake mixture.

    Turn into the prepared tins, level the top and bake in the preheated oven for about 20-25 mins, or until shrinking away from the sides of the tin and springy to the touch.

    Leave to cool in the tin, then turn on to a wire rack to become completely cold before icing.

    To make the icing: measure the cream and chocolate into a bowl and carefully melt over a pan of hot water over a low heat, or gently in the microwave for 1 min (600w microwave). Stir until melted, then set aside to cool a little and to thicken up.

    To ice the cake: spread the apricot jam on the top of each cake. Spread half of the ganache icing on the top of the jam on one of the cakes, then lay the other cake on top, sandwiching them together.

    Use the remaining ganache icing to ice the top of the cake in a swirl pattern. Dust with icing sugar to serve.

**Comment by SirAzazel** [comment]
ignore comment above, i know the guy xD

**Comment by Jofairden** [comment]
Marking the following locations if we were to do this,
[Last commit tree: [tree:1b313a796ae88ecb0618d816580daecd260f52b0](https://github.com/blushiemagic/tModLoader/tree/1b313a796ae88ecb0618d816580daecd260f52b0)]

- In Player.cs, line 39384, and line 39388. It also where life is capped, at line 39378
- In Main,cs. line 38791 specifies the mana per star. This is possibly open to new hooks, or making `UIDisplay_ManaPerStar` and `UIDisplay_LifePerHeart` public instead of private. It draws by `statManaMax2`, so the possible amount isn't limited. The same goes for life, on line 38731 life is drawn by `statLifeMax2`. The life per heart is specified on line 38694. However, it doesn't look like other lines really make use of it. Other lines are still 400 and 20 based (vanilla). See lines 38699, 38700, 38707, and 38708
- It would be neat to have draw interactions for resource in ModPlayer

**Comment by Jofairden** [comment]
Further thought, I'd like the following hooks:

- Pre/Post draw for the entire resource draws (Pre determines if drawn at all, Post runs at the end if drawn)
- Also Pre/Post draw per resource. So per life heart / golden life heart / mana crystal drawn.
- Modifying the position the resource draws at. Would be specifically useful for difference in sprite size for resource, or whatever
- A way of modifying `UIDisplay_ManaPerStar` and `UIDisplay_LifePerHeart` before/after vanilla logic
- A way of modifying the hover text. For example, now shows 500/500 for life and 200/200 for mana. Modders should be able to change the tooltip.

**Comment by Chicken-Bones** [comment]
I need use cases for all of these where replacing the entire resource draw would not be an appropriate solution. Mechanically changing the health/mana cap is good, and the mouseover can just use the mechanical value but visually? I thibk anything people add should be separate or an entire redraw or it will conflict.

I'd also like to advise designers to be more creative. There are a lot of interesting ways to create 'effective health' or 'effective mana'. The most common being damage and cost reduction respectively. Also consider reduced mana potion sickness.

Players find mechanics such as mana/health regen, free spells/replenishment on meeting certain criteria, shields, increased damage when low on health/mana to be much more engaging than simply increased caps. Consider the nebula armor for example.

Also consider interactions the life-force potion

**Comment by Jofairden** [comment]
`Pre/Post draw for the entire resource draws (Pre determines if drawn at all, Post runs at the end if drawn)`
This might actually not be needed, unless the modder would want to draw a frame around it or something. If we'd want to stop the resource from drawing we could also simply return false in the resource's PreDraw

`Also Pre/Post draw per resource. So per life heart / golden life heart / mana crystal drawn.`
Consider I have custom resource. Something like 'life shield' which I want to draw as an iron heart. I'd either want to be able to change the texture in PreDraw, or return false in PreDraw and draw manually

`Modifying the position the resource draws at. Would be specifically useful for difference in sprite size for resource, or whatever`
Says so itself. Or simply a mod that overhauls the UI, and wants to draw it somewhere else.

`A way of modifying UIDisplay_ManaPerStar and UIDisplay_LifePerHeart before/after vanilla logic`
Some mods go into thousands of resource (looking at calamity). It might be useful to have each one represent multiples of hundred.

`A way of modifying the hover text. For example, now shows 500/500 for life and 200/200 for mana. Modders should be able to change the tooltip.`
Very simply, it should just be changeable in the prospect of adding new resource mechanics. Or say a mod would like to also display life regen.

I don't think  it's fair to deny such useful hooks saying modders should just be more 'creative'. Adding new mechanics is more than creative, and ultimately is what tML is about: we go above and beyond vanilla.  Mods actually already do this, and change the resource textures and so forth, or have custom draw layers (I think?) drawing on top of regular draws. All in all, _little control_ with code that such hooks would help out with tremendously.

In terms of conflicting with other mods, it always will. Modders will always need to find a way for working well together if they're both altering resources.

@Chicken-Bones maybe check devchat as well

**Comment by SirAzazel** [comment]
@Jofairden any news on this? Even though im quite inactive cuz of RL still would be helpful to other modders too.

**Comment by Chicken-Bones** [comment]
UI overhauls will wait for 1.3.6. 
tML will only provide hooks that can be used by more than one mod at a time. Our goal is to enable /compatibility/. Mod specific hooks create maintenance bloat for us, and should be implemented using  Harmony based patching.
