### ISSUE TITLE
Error on Message Terraria.MessageBuffer

### ISSUE THREAD

**Issue by Evayr** [blushiemagic/tModLoader#339]
### Description

When loading up a Linux server of Terraria using tModLoader (latest version (v0.10.1.3)) using mono, with and without mods, the error message "Error on Message Terraria.MessageBuffer" happens after playing the game for ~5 minutes.

This message at first happens infrequently, where it eventually escalates to consistent error logging, to eventually disconnecting everyone from the server ("Connection timed out"). Vanilla without tModLoader works fine.

### Steps to Reproduce

1. Install Terraria from Steam on Linux (latest Debian Stretch in my case)
2. Copy over the Steam files over tModLoader
3. Make sure mono is installed by installing package mono-complete
4. Make sure the required files have the rights to be executed (chmod u+w tModLoaderServer.exe / Terraria.exe)
5. run mono tModLoaderServer.exe
Any world and configuration will do (with and without mods enabled).
6. Connect to the server as a client and start exploring a cave or something similar.
7. After a few minutes of gameplay, this error will pop up and will disconnect everyone connected to the server

### Reproduction frequency

12/12 so far.

### Versions

Latest version of Terraria on Steam for Linux on this date.
Latest version of tModLoader on this date (v0.10.1.3, directly downloaded from https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/ )

### Mods

With and without mods.

### Additional Information

Running on an external VPS with the latest Debian Stretch, 2GB RAM and an i7 processor.

Screenshot of it happening:
![image](https://user-images.githubusercontent.com/10324295/39628827-8cd543bc-4faa-11e8-823a-b0b73fd0692d.png)

No other information could be fetched from this issue, unless I'm forgetting a log file. There were no logs found in my ~/.local/share/Terraria/ModLoader/Logs folder.

**Comment by JavidPack** [comment]
I know many mods cause MessageBuffer errors, so just confirm again that this is with 0 mods for me if you can. 

I'm not sure what is going on, but using a system install of mono probably puts you in a configuration we can't account for. Can you try launching the server the normal way and seeing how it goes? -> just run `./tModLoaderServer`

**Comment by Evayr** [comment]
Hi, thanks for replying. :)

I can confirm that this is with 0 mods enabled. My friends and I have tried that at least 3 times.

About your second case, this are the results I get:

>root@debian:~/TerrariaSrv# ./tModLoaderServer
>monoconfig not found!
>root@debian:~/TerrariaSrv# ./tModLoaderServer.exe
>run-detectors: unable to find an interpreter for ./tModLoaderServer.exe

The only way I can run it is by using mono tModLoaderServer.exe .

**Comment by JavidPack** [comment]
hm, that monoconfig file is in both the official dedicated server files and the regular steam install that I downloaded. Not sure why it is saying it can't be found. Not sure how it could be missing or why it would be a fatal error for launching.

**Comment by JavidPack** [comment]
Someone else had the monoconfig not found problem. Turned out they were trying to install tModLoader over TShock instead of the vanilla server software: http://terraria.org/server/terraria-server-1353.zip

Make sure to install tModLoader over vanilla not tShock

**Comment by JBoughter** [comment]
Having this error pop up even on Windows. 100% sure that this is vanilla server software. 
![tmodloaderserver_2018-07-22_01-53-43](https://user-images.githubusercontent.com/1747240/43042754-17707246-8d52-11e8-9557-e8b68d2eced7.png)

Along with this, I keep getting booted from "Invalid operation at this state". One of my friends was also experiencing it too.
