### ISSUE TITLE
CLR injection support

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#341]
Many mods seek to modify small aspects of tModLoader that aren't suitable for hooks because they wish to change extremely specific behaviors. Interest has been shown in libraries that support runtime editing/patching of the IL symbols, such as Harmony.  Incorporating such a library in tModLoader itself as opposed to a Mod would reduce effort of modders seeking such functionality. We'd also need to make sure changes can be unloaded and that any example we provide will be multi-mod friendly, as tModLoader hooks strive to be with their logic.

**Comment by Jofairden** [comment]
Would be useful. Likely also makes mods doing ~~hefty~~ bad code work for mac/linux.

**Comment by Pop000100** [comment]
Have you guys seen https://github.com/pardeike/Harmony it also patching of C# code just as a alternative?

**Comment by Chicken-Bones** [comment]
We have, and it's definitely on my todolist to add method swapping support directly to tModLoader. Perhaps alongside better crash logging, and a warning when mods use the 'unsafe' modifier.

**Comment by Chicken-Bones** [comment]
21f92c8a44eb4814b4de89fc989debd1326e7e51
fcdf58d953e39236da8c5372d06ede718b3b3c80
7e5ad38c629a4b76e286b00ba8c648e2f372d693
