### ISSUE TITLE
Achievements Resetting when Cloud Save is disabled on Steam (May also affect vanilla Terraria)

### ISSUE THREAD

**Issue by HumanGamer** [blushiemagic/tModLoader#342]
### Description

Occasionally the Achievements In-Game get reset when launching Terraria.

### Steps to Reproduce

1. Disable Cloud Sync for your steam account (I have it disabled for my whole account, but you probably only need to disable it for Terraria)
2. Go to the cache and delete the exising achievements-steam.dat file (this will permanently remove your achievements in-game until you re-earn them again.) It is located here on my system: ```C:\Program Files (x86)\Steam\userdata\148099047\105600\remote\achievements-steam.dat``` It may be in a slightly different location on your PC but generally the same.
3. Exit Steam and Re-open it.
4. Launch Terraria and earn any achievements.
5. Quit the game and Quit Steam.
6. Re-launch steam and then Terraria.

### Expected behavior 

Your in-game achievements should NOT be wiped.

### Actual behavior

Your in-game achievements are now wiped.

### Reproduction frequency

Your achievements might not get wiped every time. For some reason it doesn't seem to be 100% consistent for me. Just keep trying and it should do it after a few tries. This might only happen at certain times such as every hour but I'm not 100% sure.

### Versions

tModLoader v0.14.1.4
tModLoader.v0.10.1.3

I tested the above versions, however I believe this bug also exists in vanilla Terraria.

### Mods

This happens with or without any mods.

### Additional Information

From my understanding, even when you have cloud-saving disabled through Steam, the game still tries to save and load achievements through there. This makes it use the cache. Since cloud save is disabled, sometimes Steam will realize something is messing with the cache while off-line and will try to protect it's files by resetting it's cache or something. (Note: I'm not 100% sure how steam cloud save caches work but this is what I've noticed)

After looking through the code I noticed that in Terraria.Achievements/AchievementManager.cs you will see something like this in the constructor:

```
if (SocialAPI.Achievements != null)
{
	this._savePath = SocialAPI.Achievements.GetSavePath();
	this._isCloudSave = true;
	this._cryptoKey = SocialAPI.Achievements.GetEncryptionKey();
	return;
}
```

I believe that changing the line ``if (SocialAPI.Achievements != null)`` to ``if (SocialAPI.Achievements != null && SteamRemoteStorage.IsCloudEnabledForApp() && SteamRemoteStorage.IsCloudEnabledForAccount())`` would fix the problem.

I believe this should NOT affect earning the achievements on Steam as from my understanding that is handled by SocialAPI.Achievements.StoreStats() which is called if SocialAPI.Achievements is not null.

I'd prefer not to test earning the achievements on Steam myself as I can't reset those achievements and I would like to eventually earn them legitimately.

**Comment by Jofairden** [comment]
Commit dd580ab1ca09afb6ff67e6f277b3008c5995b100 forwarded to game devs. Likely fixed in vanilla next time they release (or fixed in another fashion, we'll see). Can be reopened if still present by then.
