### ISSUE TITLE
Mobs vanishing in multiplayer

### ISSUE THREAD

**Issue by Fevix** [blushiemagic/tModLoader#353]
### Description

Mobs will, on occasion, turn invisible and invincible when struck by a player's attack

### Steps to Reproduce

1. Join a modded server
2. Get strong enemies to spawn (Minibosses work best, it seems)
3. Hit them with sword/magic/minion/etc

### Expected behavior 

Enemy takes damage, remains for further attacks

### Actual behavior

Enemy takes damage, immediately vanishes
Here, "player(s)" indicates specifically the player(s) who cannot see the enemy and does NOT apply to players who CAN still see the enemy.

- Summoned/spawned attacks from that enemy (example, the missile barrages from Mourning Wood, or the spinning scythes from Pumpking) still spawn and function, damaging the player(s) and being blocked/destroyed by player(s) attacks
- Contact damage is not applied to the player(s)
- The player(s) are incapable of damaging the enemy in question by any direct means. (I have not tested environmental/trap damage.)

### Reproduction frequency

Very often. I summoned a Pumpkin Moon using Calamity Mod (after beating one of the Calamity bosses, the Pumpkin Moon gets much more powerful) and every single Mourning Wood and Pumpking vanished on the first or second strike.

### Versions

`tModLoader v0.10.1.4`

### Mods

  "CalamityMod",
  "MagicStorage",
  "CalamityAddon",
  "BossChecklist",
  "RecipeBrowser",
  "SuperQuickRespawn"

### Additional Information

Only seems to affect modded enemies. Either enemies directly added by the mod, or vanilla enemies changed by the mod. Updating the enemy somehow (Another player attacking them, somehow managing to take contact damage or deal damage to the mob) causes the enemy to reappear.

**Comment by JavidPack** [comment]
Sounds like a mod issue. Please follow the chart below to resolve your issue.

![](http://i.imgur.com/5nGP6Qi.png)

**Comment by JavidPack** [comment]
Gonna close this as it seems as the lack of info points to a mod issue.
