### ISSUE TITLE
error CS0115: no suitable method found to override

### ISSUE THREAD

**Issue by TheGyroid** [blushiemagic/tModLoader#354]
I used the mod skeleton generator at
     [http://javid.ddns.net/tModLoader/generator/ModSkeletonGenerator.html](url)
as told to in the tutorial at
     [https://github.com/blushiemagic/tModLoader/wiki/Basic-tModLoader-Modding-Guide](url)
I filled it out took the mod folder out of the zip folder and placed it in the folder
       c:\Users\Delaney5\Documents\my games\Terraria\ModLoader\Mod Sources
as told to in the tutorial, and when I opened Terraria and hit Build and Reload in the mod sources option, I was met with the error
   
> c:\Users\Delaney5\Documents\my games\Terraria\ModLoader\Mod 
     Sources\JoshMod\Items\JoshSword.cs(8,24) : error CS0115: 
     'JoshMod.Items.JoshSword.SetStaticDefaults()': no suitable method found to override

I changed nothing in the code that I was given or the names of any files so I'm not sure as to why it's not working. The code I was given from the website is:

```
using Terraria.ID;
using Terraria.ModLoader;

namespace JoshMod.Items
{
	public class JoshSword : ModItem
	{
		public override void SetStaticDefaults()
		{
			DisplayName.SetDefault("JoshSword");
			Tooltip.SetDefault("This is a modded sword.");
		}
		public override void SetDefaults()
		{
			item.damage = 50;
			item.melee = true;
			item.width = 40;
			item.height = 40;
			item.useTime = 20;
			item.useAnimation = 20;
			item.useStyle = 1;
			item.knockBack = 6;
			item.value = 10000;
			item.rare = 2;
			item.UseSound = SoundID.Item1;
			item.autoReuse = true;
		}

		public override void AddRecipes()
		{
			ModRecipe recipe = new ModRecipe(mod);
			recipe.AddIngredient(ItemID.DirtBlock, 10);
			recipe.AddTile(TileID.WorkBenches);
			recipe.SetResult(this);
			recipe.AddRecipe();
		}
	}
}
```
I have tried finding other cases of the same issue and have tried countless ways to fix it but the only results are breaking the code or getting this same error.

I do have other mods installed but they have all been disabled as I tried to experiment with making a first mod.

Thanks in advance for your response and I hope I have provided enough information to locate the problem and provide a solution.

**Comment by TheBruhCats** [comment]
change this

public override void AddRecipes()
		{
			ModRecipe recipe = new ModRecipe(mod);
			recipe.AddIngredient(ItemID.DirtBlock, 10);
			recipe.AddTile(TileID.WorkBenches);
			recipe.SetResult(this);
			recipe.AddRecipe();
		}

to

public override void AddRecipes()
		{
			Recipe recipe =  CreateRecipe();
			recipe.AddIngredient(ItemID.DirtBlock, 10);
			recipe.AddTile(TileID.WorkBenches);
			recipe.Register();
		}
