### ISSUE TITLE
TileLoader.PostDraw called on inactive tiles

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#357]
This should be fixed. I think the second calling of TileLoader.PostDraw is incorrectly positioned, but the gotos are a little confusing to decipher. 

The effect of this is apparent with doors, since they simply set the tile inactive and leave the tile type value there when closed.

**Comment by Jofairden** [comment]
I'd say let's save this for 1.3.6, see if any of that code changed and we might fix it actually by just fixing the patches with a bit of luck.
