### ISSUE TITLE
Windows 10 1803 seems not working with the mod loader

### ISSUE THREAD

**Issue by SongRb** [blushiemagic/tModLoader#359]
### Description

After update my Windows 10 to 1803 version, the terraria.exe cannot be launched

### Steps to Reproduce

1. Update Windows 10 to 1803
2. Click terraria.exe in local file
3. Wait for the 'Not responding message'

### Expected behavior 

The game should launch normally

### Actual behavior
![2018-06-08](https://user-images.githubusercontent.com/15308237/41138428-d5c0066e-6b13-11e8-9ea9-9a002f763572.png)

### Reproduction frequency

Each time.

### Versions

`v0.10.1.4 tModLoader`

### Mods
Chinese mod

**Comment by JavidPack** [comment]
I have been on 1803 for a while with no problems. Is there anything else you can think of that has changed?

**Comment by SongRb** [comment]
Alt+Enter can save this problem.

**Comment by Jofairden** [comment]
One thing you should do is make sure Focus Assist is disabled. It causes many issues. [See here.](https://www.windowscentral.com/how-use-focus-assist-reduce-distractions-windows-10-april-2018-update)
Also, try updating your gpu drivers.

**Comment by SongRb** [comment]
@Jofairden Thanks for your advice, I have resolved that issue by Alt+Enter.
