### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Buader** [blushiemagic/tModLoader#365]
Description

Crashes whenever I open tModLoader at the Finding Mods part of loading. Can't get in to turn off or delete mods and it crashes before any movement on the loading bar can happen. This is what was int he crash log
6/17/2018 3:26:24 AM
System.DllNotFoundException: Unable to load DLL 'CSteamworks': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

Steps to Reproduce

Not sure as it was running fine then I turned it off for about 2 hours and it stopped working entirely without changing anything. 

Expected behavior 

Loads fine.

Actual behavior

Crashes before anything can load.

Reproduction frequency

Can not get into tModLoader at all.

Versions

v0.10.1.4 tModLoader (Downloaded 6/17/2018)

Mods

Thorium, Calamity, Tremor, Boss Checklist, Wing Slot, and Cheat Sheet and can't turn off any mods.

Additional Information

I did reinstall the Loader after it didn't work but the issue didn't change at all. It also stopped working after lagging at the Celestial Events thoough

**Comment by DarkLight66** [comment]
This one of the issues answered in the FAQ: https://github.com/blushiemagic/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#systemdllnotfoundexception-unable-to-load-dllcsteamworks
