### ISSUE TITLE
monoconfig not found!

### ISSUE THREAD

**Issue by CrazyFrogAxelF** [blushiemagic/tModLoader#368]
### Description

When I attempt to run tModLoaderServer on a Mac I get the message monoconfig not found!
### Steps to Reproduce

1. Manually install tModloader onto a Mac.
2. Run tModLoaderInstaller.jar
3. Run tModLoaderServer

### Actual behavior
It displays the error monoconfig not found!

### Reproduction frequency
I've tried this multiple times but every time I get the same issue.

### Versions

tModLoader v0.10.1.4
### Mods
All mods are currently disabled.

### Additional Information
Terraria v1.3.5.2

**Comment by CrazyFrogAxelF** [comment]
I tried what you recommended when this issue came up before but it didn't work. Are there any other ways?

**Comment by Chicken-Bones** [comment]
Come chat to us on Discord if you still need help with this, but whoops, it's a year old
