### ISSUE TITLE
Error when compiling Example Mod

### ISSUE THREAD

**Issue by TSAR-0** [blushiemagic/tModLoader#369]
### Description

Attempting to Build Example Mod causes an error in compilation

### Steps to Reproduce

1. Build Unedited Example Mod

### Expected behavior 

The mod successfully builds.

### Actual behavior

3 errors appear in Compile Errors.txt
```
c:\Users\rocke\Documents\My Games\Terraria\ModLoader\Mod Sources\ExampleMod\NPCs\ExampleChestSummon.cs(28,24) : error CS0115: 'ExampleMod.NPCs.ExampleChestSummon.UpdateAutopause()': no suitable method found to override

c:\Users\rocke\Documents\My Games\Terraria\ModLoader\Mod Sources\ExampleMod\NPCs\ExampleGlobalNPC.cs(227,24) : error CS0115: 'ExampleMod.NPCs.ExampleGlobalNPC.PreChatButtonClicked(Terraria.NPC, bool)': no suitable method found to override

c:\Users\rocke\Documents\My Games\Terraria\ModLoader\Mod Sources\ExampleMod\NPCs\FallenSoul.cs(67,24) : error CS0115: 'ExampleMod.NPCs.FallenSoul.CanChat()': no suitable method found to override

```

### Reproduction frequency

Every time, after reboot, after deletion and re installation. Everything is fresh.

### Versions

Terraria v1.3.5.2
tModLoader v0.10.1.4

### Mods

None

### Additional Information
Just starting to get into this stuff, not sure where to go from here with this error, google searches lead to no avail either.

**Comment by JavidPack** [comment]
If you want to build ExampleMod, use the ExampleMod from the release: https://github.com/blushiemagic/tModLoader/releases

What you are trying to build has 0.10.1.5 methods in it, so it won't work.

**Comment by TSAR-0** [comment]
Oh, I didn't notice there was a difference in versions from the GitHub release and the release on the forum. Ty.
