### ISSUE TITLE
(Sometimes) Main.rand is null when Mod.Load is called

### ISSUE THREAD

**Issue by strongrex2001** [blushiemagic/tModLoader#374]
### Description
Sometimes it's okay, but sometimes Main.rand is null when Mod.Load is called, which caused an Exception.

### Steps to Reproduce

1. You need some bad luck.
2. Call Main.rand.Next(10); in Mod.Load()
3. And you got an Exception.

### Expected behavior 
Main.rand is an instance of UnifiedRandom and the call returns a random integer.

### Actual behavior
Main.rand is null and the call throws a NullReferenceException.

### Reproduction frequency
Before 10%.
Today I tried about 10 times and 100% (maybe such bad luck...), so I came here.

### Versions
tModLoader v0.10.1.4 (currently the newest)

The tModLoader version should be notified in the bottom left corner when in the main menu. Follow this format: `vX.X.X.X tModLoader` or `tModLoader vX.X.X.X`

### Mods
Only my mod.

### Additional Information
MessageBox.Show("Rand is null: " + (Main.rand == null));
Just before the Exception code and I got true.
I've judged Main.dedServ.

**Comment by JavidPack** [comment]
This is by design. Too many people use Main.rand in various SetDefaults methods or constructors which could lead to unpredictable and desyncing behavior. An easy way to deal with this was make Main.rand null to trigger the null reference error and then teach them proper ways to do what they intend to do. If you need rand, just instantiate it if it is null.

**Comment by strongrex2001** [comment]
(OwO) Okay, but this mechanism seem not so stable as I only got this Exception 'sometimes' haha

**Comment by Chicken-Bones** [comment]
yeah, Main.rand probably shouldn't be used during setup, the fact that it's non-null sometimes means someone might be initialising it
