### ISSUE TITLE
Tmodloader crashing on "finding mods"

### ISSUE THREAD

**Issue by Skxullo** [blushiemagic/tModLoader#376]
Whenever i try to open Terraria "tmodloader version" it just sais Terraria: (Not Responding) Then it boots up a debug and i press close program. Can someone help me please?

**Comment by Jofairden** [comment]
You can first try 2 things: hold left shift when the game starts loading
or go to your documents My Games/Terraria/ModLoader/Mods and remove the enabled.json file.
Let us know

**Comment by Skxullo** [comment]
what does left shift do?

**Comment by Jofairden** [comment]
Sorry for the late reply, left shift makes the game not load your mods. This allows bypassing the loading screen.

**Comment by Skxullo** [comment]
When i load terraria up and hold left shift everything is fine, but when i
go into a world it crashes.
Help?

**Comment by Jofairden** [comment]
How does it crash? Do you get an error? Does it just freeze? Does it also happen with other worlds?

**Comment by Skxullo** [comment]
Like when i load into the game, it freezes then showed the error file. This
also happens with other worlds.

**Comment by Jofairden** [comment]
Okay, but can you show the error?
