### ISSUE TITLE
Invisible friends in multiplayer

### ISSUE THREAD

**Issue by Capi3210** [blushiemagic/tModLoader#379]
Hey

I'm actually playing Terraria Overhaul with my friend and there is only one big problem.
After some minutes in the game my friends become invisible. It can be fixed if they reconnect but its not long time solution.

Mods whe use are:
Calamity
Thorium
Spirit
GRealm
Base Mod (required for GRealm)
Yet Another Boss Health Bar
Boss Checklist
Terraria Overhaul Mod

I would be really happy if someone help me.

**Comment by Jofairden** [comment]
Closed until further notice (this is likely a problem caused by a mod, not tML)
