### ISSUE TITLE
'Ghost' NPC with type 0

### ISSUE THREAD

**Issue by strongrex2001** [blushiemagic/tModLoader#381]
I'm sorry for not using the issue template, because it's just a strange behaviour, not an ordinary 'bug', and seems to be a problem from vanilla Terraria.
In a projectile AI, I wanted to fetch a list of NPCs that had one of my buffs on. When I call Main.npc.Where with NPC.HasBuff in the condition, it threw an IndexOutOfBoundsException in FindBuffIndex. I was frustrated, and checked your code. I found that it seem to be buffimmune. I outputed the length in the Where lambda (I created a function that outputs and returns true, and && in the condition) and got 206, which is the length in vanilla terraria. With my mod it should be 306.
But strangely, this npc is active but not calling GlobalNPC.AI. It does not have a name,and has a type of 0. It seems that it is not initialized by tModLoader.
An appearant solution is to check npc.type==0, but I'm curious about it.
Could you explain to me why is this NPC active, and why we need an NPC here?
If this NPC is not important, would you mind removing it from Main.npc in the next version?

**Comment by JavidPack** [comment]
Can you provide a minimum complete reproducible example for us? Everything in Main.npc should have the correct buffImmune array, it would be good to fix this.

**Comment by strongrex2001** [comment]
You just need to create any mod buffs and call Main.npc.Where((n) => n.active &&n.HasBuff(mod.BuffType<...>())) in ModProjectile.AI. The reproduction rate here seem to be 100%.

**Comment by strongrex2001** [comment]
I'm really sad and I feel sorry for not being able to present an entire reproducible example :sob:. The repairing shop says my computer has got some more problems and I should wait for another 2 days... Could you use ExampleMod to reproduce the problem? Just need to add
```
Main.npc.Where(n => n.active && n.HasBuff(mod.BuffType("Nullified")));  // Or some other buffs
```
to any of ModProjectile.AI().

**Comment by JavidPack** [comment]
I tried this but didn't experience any exceptions. When you get around to this, can you verify that this happens with a fresh launch of tmodloader where only examplemod is enabled?

**Comment by strongrex2001** [comment]
I'm really sorry.. We tried for a long time but we cannot reproduce it... There seems to be somewhere unknown here in my mod producing this strange behavior...

**Comment by JavidPack** [comment]
K, feel free to reopen this if you find a reproducible situation.
