### ISSUE TITLE
Error on Message Terraria.MessageBuffer with /roll and /players

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#390]
Tested with 0 mods enabled. Both commands cause an error in the server console and nothing appears on the client. Interestingly `/roll a` does the roll correctly and `/players a` also works. Basically adding a bogus argument to the command works. Confirmed to be working in vanilla 1.3.5.3

**Comment by Jofairden** [comment]
Might this be because of ModCommand? I suppose that's the first place we should look.

**Comment by JavidPack** [comment]
Yeah, I think it is. We probably have a parsing error somewhere in our logic
