### ISSUE TITLE
A visual glitch in Mod Browser

### ISSUE THREAD

**Issue by jvschiavo** [blushiemagic/tModLoader#391]
### Description

There is a visual glitch in Mod Browser in Brazilian Portuguese (possible other languages as well)

### Versions

Terraria 1.3.5.2
tModLoader v0.10.1.5

### Mods

None

### Additional Information

![20180723022413_1](https://user-images.githubusercontent.com/20977075/43059123-605e1272-8e21-11e8-8783-fdf1d274f157.jpg)
![20180723022953_1](https://user-images.githubusercontent.com/20977075/43059124-6079573a-8e21-11e8-8b7b-6762c6b066a7.jpg)

**Comment by jvschiavo** [comment]
Just noticed it happens on some other places too.

![20180723024102_1](https://user-images.githubusercontent.com/20977075/43059248-fb5649c0-8e21-11e8-8f7b-8b5c40d80d1d.jpg)
![20180723024120_1](https://user-images.githubusercontent.com/20977075/43059249-fb733d14-8e21-11e8-9400-3d5f448f742e.jpg)

**Comment by Jofairden** [comment]
Yeah, we'll need to recalculate the sizes and offsets based on the translations.

**Comment by JavidPack** [comment]
Oh yeah, I fixed this in 80cc3b892c53f8213731a48f3204a30b7d51f1ad

Once the next releaser/open beta is out, it would be neat if you could revisit this issue and let us know anything you notice that still needs changing.

![image](https://user-images.githubusercontent.com/4522492/48248836-2e96fc00-e3b6-11e8-8479-a692165d5144.png)
![image](https://user-images.githubusercontent.com/4522492/48248878-4e2e2480-e3b6-11e8-9f9c-56dd6beeae02.png)
