### ISSUE TITLE
"host and play" causes game to crash

### ISSUE THREAD

**Issue by IanQS** [blushiemagic/tModLoader#402]
### Description

"Host and Play" Causes the game to crash (with and without mods)

### Steps to Reproduce

1. Click on Multiplayer
2. Click on "Host and Play"
3. Choose character and world
4. Server Settings: "Enabled, Friends, Off"
5. Type password(or not) 
6. Click "Accept" and the game crashes

### Expected behavior 

Game doesn't crash

### Actual behavior

Game crashes with no error log showing up or anything

### Reproduction frequency

Every time

### Versions

Ubuntu 18.04(?)
Terraria (1.3.5.2)
TmodLoader (0.10.1.5)

### Mods

Thorium
Overhaul

Both tested independently of each other, and tested when no mods are enabled

### Additional Information

Terraria installed via Steam

**Comment by Jofairden** [comment]
Have you checked inside Documents/My Games/Terraria/ModLoader/Logs ? There might be some errors in there.

**Comment by Jofairden** [comment]
Friendly reminder if you can provide us with logs or other additional info. This seems like a specific problem.

**Comment by IanQS** [comment]
Hey! Sorry, yeah I've been swamped with stuff and this fell by the wayside. I'll try and test it within the next 48 hours and get back to you. Thank you for following up!

**Comment by Jofairden** [comment]
Stale issue. @IanQS if you still experience issues, feel free to contact us again or reopen the issue.

**Comment by heav-4** [comment]
having the same problem. almost identical setup but with different mods.
