### ISSUE TITLE
First localization token in lang file does not work correctly

### ISSUE THREAD

**Issue by VectorAdw** [blushiemagic/tModLoader#403]
### Description

First localization token in lang file does not work correctly

### Steps to Reproduce

1. Create two new ModItems that have minimal required info
2. Add two lang files (eg. en-US, pl-PL)
3. Add ItemName translations for both of them in both files
4. In one of lang files add comment in first line, second leave as is
5. Run game and check both items on both languages

### Expected behavior 

All tokens work

### Actual behavior

First token in lang file does not

### Reproduction frequency

Every time

### Versions

tModLoader v0.10.1.5

### Mods

Only one I develop

### Additional Information

One picture is worth a thousand words ([gfycat link](https://gfycat.com/ReadyAthleticCassowary)).
Used code samples ([GDrive link](https://drive.google.com/open?id=1R2r09E-Iw05S_j_OovaYMfiabI2RZ5mv)).

**Comment by JavidPack** [comment]
Your files were encoded as UTF-8-BOM. Changing them to just UTF-8 fixed it.

![](https://i.imgur.com/Y6cr6Vf.png)

I'll make a note somewhere so this distinction is known.

**Comment by VectorAdw** [comment]
You're right, thanks for the advice!
