### ISSUE TITLE
How about add default implementation of mod player sync

### ISSUE THREAD

**Issue by AxeelAnder** [blushiemagic/tModLoader#406]
Few mods implement it though it seems no problem when playing in multiplayer.

**Comment by Jofairden** [comment]
Can you share more details? I don't know what you are suggesting.

**Comment by AxeelAnder** [comment]
I'm sorry for my poor English. I'm working on something about server side character and I find that clients and the server don't sync mod's player data. If tml can sync it, it will be convenient. Otherwise I need to make a mod for syncing mod's player data.

**Comment by Chicken-Bones** [comment]
We don't sync data because networking is something modders need to carefully consider based on their knowledge of their mod. If we did automatic syncing it would use up a lot of unnecessary bandwidth and cause hard to track bugs

**Comment by AxeelAnder** [comment]
OK, thanks a lot
