### ISSUE TITLE
ExampleMod Request: Adding additional item to existing RecipeGroup

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#408]
If this is possible, we should add an example of this. We'd also want to verify that the implementation works regardless of mod load order and that material and other behind the scenes things account for the new items correctly.

**Comment by JavidPack** [comment]
```cs
public override void AddRecipeGroups()
{
	RecipeGroup WoodGroup = RecipeGroup.recipeGroups[RecipeGroup.recipeGroupIDs["Wood"]];
	WoodGroup.ValidItems.Add(ItemType<Items.CarKey>());```

Pretty sure this works, but I'll test later.

**Comment by Jofairden** [comment]
This is cool/useful, nice.
