### ISSUE TITLE
Weapon Racks actualy reset all global item properties

### ISSUE THREAD

**Issue by PlexusDuMenton** [blushiemagic/tModLoader#412]
### Description

Weapon Racks actualy reset all global item properties
When you have an item with value in custom global items and you actually put it in weapon rack and pick it up all global item value are reset as if the item was just created

### Steps to Reproduce

1. Pick an item with global item variable
2. Put item into Weapon rack
3. Pick up back item
4. Global item values are reseted

### Expected behavior 

Weapon to keep actual values when picked up

### Actual behavior
Weapon value are reseted

### Reproduction frequency

Allways

### Versions

tModLoader v.0.10.1.5

### Mods

Another Rpg Mods
but would happen with any other mods using instanced global item

### Additional Information

None

**Comment by DarkLight66** [comment]
Already known: https://github.com/blushiemagic/tModLoader/issues/207
