### ISSUE TITLE
No Suitable Method Found to override

### ISSUE THREAD

**Issue by CanadianOwl** [blushiemagic/tModLoader#415]
When I try to build my mod it pops up with an error message saying
An error occured while compiling a mod

C:\Users\Name\Documents\My Games\Terraria\ModLoader\Mod Sources\TutorialMod\Enemies\Tutorial.cs(9,31) : error CS0115: 'TutorialMod.Enemies.TutorialEnemy.CanSpawn(Terraria.ModLoader.NPCSpawnInfo)': No Suitable Method Found to override

How do I fix?

**Comment by JavidPack** [comment]
That method was renamed to SpawnChance long ago: http://blushiemagic.github.io/tModLoader/html/class_terraria_1_1_mod_loader_1_1_mod_n_p_c.html#ae7713bbbd313012944b958e8eafc35e0

Try to stick to the wiki here and ExampleMod, don't expect Youtube tutorials to be up to date.
