### ISSUE TITLE
Add Mod Skeleton Generator

### ISSUE THREAD

**Issue by Chicken-Bones** [blushiemagic/tModLoader#418]
In the Mod Sources menu, we should add a "New Mod" button, where you enter a name and it generates a basic mod, with a single example item. Should include:

`build.txt` with comments for all available options
`ModName.cs` mod class, with a few directions on getting started in comments (link to a guide?)
`Items/CustomSword.cs` with a default recipe (maybe some wood and iron
`Items/CustomSword.png`
`ModName.csproj` fully linked and ready to go, with the command line build. 
`ModName.csproj.user` with debug settings (client)

It's desirable to have it in-client so all libraries can be linked properly. All embedded libraries will need to be extracted to another directory (perhaps ModCompile/EmbeddedLibraries)
Currently most people don't need to use zip/mp3/cecil/json, but they won't be able to access the new logging in VS without log4net, or the hooking support that's getting directly added for next release with MonoMod

**Comment by Jofairden** [comment]
I think alternatively, we should provide a Visual Studio template that fits the needs of a bare-bones mod (as described above) which people can use to generate their mod project by template. Implementing this into the client is basically client bloat for something the client /doesn't really have to/ be capable of doing.

**Comment by Jofairden** [comment]
For now, a separate application (JAR) has also been made: https://github.com/tModLoader/mod-skeleton-generator
Of course, having this in game is still nice.

**Comment by Chicken-Bones** [comment]
Current in-game generator is pretty good (beta 2)
