### ISSUE TITLE
New Sprite Helper

### ISSUE THREAD

**Issue by Jerkymushroom** [blushiemagic/tModLoader#419]
### Description

This is my first time uploading on GitHub and I have no idea where I should upload my new sprite helper for tModLoader. Attached is the folder for my program.
[tModLoaderHelper.zip](https://github.com/blushiemagic/tModLoader/files/2439583/tModLoaderHelper.zip)

**Comment by JavidPack** [comment]
You should make a thread on the Terraria forum: https://forums.terraria.org/index.php?forums/client-server-mods-tools.116/

Once you have a thread, you can link to it if you add it to the wiki here: https://github.com/blushiemagic/tModLoader/wiki#utilitiesother

**Comment by Jerkymushroom** [comment]
Ok
