### ISSUE TITLE
ErrorLogger Obsolete

### ISSUE THREAD

**Issue by Chicken-Bones** [blushiemagic/tModLoader#420]
With the new log4net system, error logging is much simpler and more consistent. I've cleaned up all the mod building and loading code, but I'm leaving the mod browser and other locations to the other devs. Marking this for next release.

We'll leave the single public method with an [Obsolete] tag, and search the stack for the caller and forward it to `Mod.Logger`

**Comment by Jofairden** [comment]
Might look into additional logging this weekend (if I don't feel drained again ^^)

**Comment by Jofairden** [comment]
Done and done.
a4438e4
6a360c5

**Comment by Jofairden** [comment]
Actually, this breaks mods, how'd you want to forward existing Log calls? @Chicken-Bones

**Comment by Jofairden** [comment]
Fixed mods breaking
ab57fff
(Forward ErrorLogger.Log to new Logging system using the calling assembly)
