### ISSUE TITLE
Errror in Mod Browser is unclear

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#423]
### Description

The error in the browser is unclear:
![](https://cdn.discordapp.com/attachments/436261964017303553/497132589480411146/unknown.png)

We get the recurring question "browser is offline, how fix?" a lot. The problem is that the loading icon stays, to people this can indicate it is a problem on their end because it seems to remain loading, even after saying Offline (Unknown)

Also, the (Unknown) part is not necessary, OFFLINE is enough.

### Steps to Reproduce

1. Block the browser website if needed
2. Else try when the browser is actually offline

### Expected behavior 

Loading icon should go away, a descriptive text should be entered about the problem.
The text should say if the client indicates a problem on the user's end, not a different status code.

### Reproduction frequency

Always

### Versions

Version since browser introduce

### Mods

None

**Comment by PoshPoro** [comment]
I cant play at all if this isnt fixed soon, is there any way I can fix it on my own?

**Comment by Jofairden** [comment]
@PoshPoro the browser is currently down which has nothing to do with this issue, this issue is about the text being unclear

**Comment by JavidPack** [comment]
![image](https://user-images.githubusercontent.com/4522492/48326539-1d88fd80-e5f7-11e8-857e-ca3a0e82eac1.png)
