### ISSUE TITLE
Tmodloader 0.10.1.5 failed to start up with win xp system

### ISSUE THREAD

**Issue by qq1176321897** [blushiemagic/tModLoader#425]
### Description

The latest version of tmodloader crashes with Windows XP system
(I'm sure that I have closed every anti-virus software and there should not be a bitdefender for the xp system.

### Steps to Reproduce

1.  Have a computer with winxp with .net4.0 and xna4.0redist installed
2. open terraria mod loader

### Expected behavior 

The tmodloader should starts up normally.

### Actual behavior

the tmodloader gives me an message
![image](https://user-images.githubusercontent.com/34051396/46570205-3fa5b500-c993-11e8-9bef-f51bc54f74c2.png)

### Reproduction frequency

Always

### Versions

tmodloader 0.10.1.5
p.s. it works well with 0.10.1.1

### Mods
None.

**Comment by qq1176321897** [comment]
I have tried that but it has no effect. In fact, I got this error message on three different computers with winxp system and all of them are new to terraria.

**Comment by Chicken-Bones** [comment]
As much as we'd love to solve this bug, it may not matter soon thanks to the following announcement
https://support.steampowered.com/kb_article.php?ref=1558-AFCM-4577

**Comment by qq1176321897** [comment]
Thanks a lot. I'll try to upgrade my operating system and try again.
