### ISSUE TITLE
Multiplayer Damage Syncing broken

### ISSUE THREAD

**Issue by DanYami** [blushiemagic/tModLoader#429]
### Description
Multiplayer Damage Syncing breaks when damage exceeds signed 16 bit integer limit (32767)

### Steps to Reproduce
1. Use an item that deals over 32767 damage in Multiplayer
2. Attack an enemy with it
3. Enemy will take visual damage but never die

### Expected behavior 
The enemy should die

### Actual behavior
Damage is not being synced, leaving the enemy alive

### Reproduction frequency
100%

### Versions
tModLoader v0.10.1.5

### Mods
No mods are needed to achieve this, you only need to have an item that deals that much damage

### Additional Information
Damage has to be over 32767

**Comment by Jofairden** [comment]
@Chicken-Bones we should look at this for 0.11, make sure it's no longer an issue

**Comment by Chicken-Bones** [comment]
Code analysis indicates this is a projectile only problem, please confirm.

**Comment by Agrair** [comment]
No, I think it’s damage from anything. From what I saw, when I checked a couple months ago, was that the issue is just that to sync damage, Terraria sends packets containing “Int16”s, which cause the sync to break cuz one client registers more damage than the others.

**Comment by Chicken-Bones** [comment]
Packet id?

**Comment by Agrair** [comment]
28, I think. On the discord, search for this issue’s link, and you should find a discussion between jopojelly, Dark;Light, and myself: and some point Dark;Light mentions the packet ID and the fix.

**Comment by JavidPack** [comment]
Bug confirmed and fixed: https://gfycat.com/SelfreliantDarlingKillerwhale
