### ISSUE TITLE
Weird UI Click behavior 

### ISSUE THREAD

**Issue by Exeton** [blushiemagic/tModLoader#432]
### Description

The onClickEvent in UIElement's is only called in the first drawn UI. This means the click event isn't fired for the top layer of the UI, but instead the bottom layer first.

### Steps to Reproduce

Example code in a subclass of UIState in OnInitialize()

`base.add(basePanel);`
`base.add(someText);`
`base.add(myCustomItemSlot);`

I've also tried the following

`basePanel.add(someText);`
`basePanel.add(myCustomItemSlot); `
`base.add(basePanel);`

### Expected behavior 
Click events should be passed on to all children of a parent if the child falls within the clicked region (i.e. multiple UI Elements are overlapping, they should all receive the click event). Or the UI element that is drawn last (the one that's on top) should receive the click event.

### Actual behavior
The first drawn GUI element is given the click event, and UIPanel does not pass the click event onto its children. This means that if you have a CustomItemSlot being drawn ontop of a UIPanel, the click event is fired for the UIPanel, but not the CustomItemSlot.

### Reproduction frequency
100% of the time

### Versions
tModLoader v0.10.1.5

### Mods
Just the mod where the bug occurs

**Comment by JavidPack** [comment]
Overlapping UIElements are not supported by the UI system (within the same level of nesting). Nested elements, however, are. 

In your example you should find that this works:

myCustomItemSlot.add(someText);
basePanel.add(myCustomItemSlot); 
base.add(basePanel);

If this doesn't work, this question is probably better suited for the discord chat so we can go back and forth quickly: discord.me/tModLoader

**Comment by Exeton** [comment]
Thanks, there was a bug in my code.
