### ISSUE TITLE
Netcode Guides / Examples needed

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#439]
See title.

**Comment by JavidPack** [comment]
Fixed in 7f42c37471480678e3305e7937547cb76d52187c

Video: https://gfycat.com/FickleWastefulIrishdraughthorse

**Comment by Jofairden** [comment]
I think what we have is good right now. We can always expand on it
[/wiki/Multiplayer-Compatibility](wiki/Multiplayer-Compatibility)

**Comment by Chicken-Bones** [comment]
Nice work
