### ISSUE TITLE
Mod Development on Mac/Linux

### ISSUE THREAD

**Issue by Chicken-Bones** [blushiemagic/tModLoader#442]
With the recent adoption of Roslyn and .NET 4.6 for building mods, alongside the v4.0 Client Reference Assemblies, mod building on mono platforms needs revisiting.

**Comment by Dilnu** [comment]
Hi, the people on the discord server suggested I explain my experiences with attempting to mod on Mac.

I started by following the standard tutorial and got an error beginning with Error running mcs: Cannot find the specified file.

I posted this in the discord and got directed to https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/page-525#post-1001200

I downloaded Visual Studio for Mac and after some difficulties successfully got it to build mono.dll.

Following that I tried setting nobuild = true in build.txt and building again inside terraria. I got a message about needing mono.dll and windows.dll or all.dll so I followed the instructions there and produced a dll file without any mono or windows specific dependencies and renamed it all.dll

Then my game started to crash whenever I tried to build giving this error: https://justpaste.it/3gy6f

**Comment by Chicken-Bones** [comment]
As of https://github.com/blushiemagic/tModLoader/commit/32763dc8f5002174a0f52eeca7c080ed58f116f1 mods can be built both in game, via command line and using `msbuild /restore Mod.csproj` on all platforms. Once you get through the dev mode setup UI it should work
