### ISSUE TITLE
(Hair) dye issues

### ISSUE THREAD

**Issue by Jofairden** [blushiemagic/tModLoader#443]
### Description

Numerous problems:

- Dyes are not unloaded well
- Hair dye is stored on the player save, but not handled by tML correctly.

**Comment by DarkLight66** [comment]
Commit https://github.com/blushiemagic/tModLoader/commit/aa655a3039c93e8978e429da0605c89462f4e704 makes changes that allow removing Armor dyes manually, but it doesn't reset `_shaderDataCount`, and the changes don't affect Hair dyes. In my opinion, removing dyes should be handled by tmodloader itself after mods unload.
Also, if the dye limit could be increased from 255 somehow, that'd be great.

**Comment by Chicken-Bones** [comment]
0de88ac41c8396cbf59a4154a3aeb746c014cab1 fixed, mods don't need to remove their shaders/effects anymore.

As for the dye limit, there's the 255 limit check but I'm not sure what other systems that's tied into. You're welcome to change it and submit a PR

**Comment by DarkLight66** [comment]
The part about modded hair dyes not saving correctly for players is still a problem. Basically, just like modded items, hair dyes added by mods may get different ids between sessions depending on mods loaded, and these ids are saved to the player file directly.
