### ISSUE TITLE
Having more than 50-51 town NPCs breaks the housing UI

### ISSUE THREAD

**Issue by SaiyanKirby** [blushiemagic/tModLoader#461]
### Description
After acquiring too many town NPCs, the housing UI stops functioning properly. It doesn't draw every NPC face, and other UIs may stop drawing such as the coin/ammo slots, or chests or shops. Killing NPCs to bring the number back down stops the issue.

### Steps to Reproduce
1. Download several mods (see the mod pack below) that add town NPCs
2. Spawn as many of them as you can, at least over 50-51. Make sure they're NPCs that can be housed, not like the vanilla cursed old man.
3. Open the housing UI and try opening a chest or shop. It won't draw the contents.

### Versions
Using tModLoader v0.10.1.5

### Mods
The mods I have active while testing this issue:
[
  "AlchemistNPC",
  "CalamityMod",
  "CheatSheet",
  "Fargowiltas",
  "imkSushisMod",
  "Luiafk",
  "SacredTools",
  "SolutionsMod",
  "TerraAvaritia",
  "ThoriumMod"
]

### Additional Information
My screen resolution is 1920x1080, played in windowed mode.

**Comment by Agrair** [comment]
If that many NPCs are spawning, my personal opinion would just be to not have that many.
