### ISSUE TITLE
Freezing on Mac while loading

### ISSUE THREAD

**Issue by AvianGang** [blushiemagic/tModLoader#464]
### Description
Re-Logic screen comes up, fades away into darkness then freezes.

### Steps to Reproduce
1. Download tModLoader and install on Mac
2. Open Terraria through Steam
3. Hope that it works and cry when it doesn't

### Expected behavior 
Game starts as normal with tModLoader logo being in corner

### Actual behavior
Never-ending darkness and game freeze than can only be solved with a force quit

### Reproduction frequency
90%

### Versions
tModLoader 0.10.1.5

### Mods
No mods installed

### Additional Information
Similar to #237 and #400 **but it still happens after the supposed fix for those two bugs.** No crash report or error message is displayed- hopefully it's fixed soon!

**Comment by JavidPack** [comment]
It's fixed in the next release.
