### ISSUE TITLE
Visual Studio can't find the pdb

### ISSUE THREAD

**Issue by MrDj200** [blushiemagic/tModLoader#472]
### Description

When I try to run Terraria from VS2017 with Debugging, it runs but it can't find the pdb.

### Steps to Reproduce

N/A (It seems it's a local issue)

### Expected behavior 

Start Terraria with PDB.

### Actual behavior

VS2017 is not finding the PDB, even though I added `includePDB = true` to the build.txt

### Reproduction frequency

100%

### Versions

tModLoader v0.10.1.5
### Mods

N/A

### Additional Information

- My Terraria Game Path: `C:\SteamLib\steamapps\common\Terraria`
- Post-build event command: `C:\SteamLib\steamapps\common\Terraria\tModLoaderServer.exe -build "$(ProjectDir)" -eac "$(TargetPath)"`
- [Output from VS17 when starting Terraria](https://gist.github.com/MrDj200/aca89aeeb7008f369f57a2ff71453c30)
- [My build.txt](https://gist.github.com/MrDj200/1176de4eb6db8921bf744d6f4f50d189)
- [The File Tree](https://gist.github.com/MrDj200/6f7180a91407e31bdeed34614a6ac902)

P.S.: I know this is probably just something local, but I still hope someone can help me. :)

-Dj

**Comment by Chicken-Bones** [comment]
Send output from VS postbuild. Also come ping me in Discord tomorrow (I'm
in bed at the moment)

**Comment by Chicken-Bones** [comment]
In the output window when building. I'm GMT+10, anytime 10 hours from now is good (10am-10pm)

**Comment by MrDj200** [comment]
The Output when Rebuilding the Project:
```1>------ Rebuild All started: Project: NpcHub, Configuration: Debug Any CPU ------
1>  NpcHub -> C:\Users\David\Documents\My Games\Terraria\ModLoader\Mod Sources\NpcHub\bin\Debug\NpcHub.dll
1>  Reading Properties: NpcHub
1>  Loading pre-compiled Windows.dll with edit and continue support
1>  Compiling NpcHub for Mono...
1>  Building NpcHub...
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by Chicken-Bones** [comment]
That looks correct, I'll need to sort it out with you on Discord tomorrow

**Comment by MrDj200** [comment]
Allright. Thanks in advance and have a good night!
