### ISSUE TITLE
Attempting to Delete Active Mod bug

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#475]
When using the Mod->More Info->Delete button on an active mod, the game goes into an infinite exception loop because the file is still in use

We either need to make the button more capable, disabling the mod and releasing the file lock, or hide the button unless the mod isn't currently loaded.

**Comment by Chicken-Bones** [comment]
I vote hide it, or disable it with a tooltip, "Mod must be disabled before it can be deleted"

**Comment by Jofairden** [comment]
Can't we have the button disable the mod itself and then delete + reload?

**Comment by Chicken-Bones** [comment]
Technically, yes

**Comment by Jofairden** [comment]
Wouldn't that be better rather than obfuscating (or making it more difficult than necessary ) ?
[My point being, we are making the feature harder to use because the mod is enabled, do we want that?]
