### ISSUE TITLE
Add mod controlled hiding of inventory crafting menu

### ISSUE THREAD

**Issue by DaxterSpeed** [blushiemagic/tModLoader#476]
### Description
Currently there's no way for a mod to hide the crafting menu that shows when you open the player inventory. The player inventory is rendered in many different contexts, but the inventory crafting menu is only hidden when the player inventory is enabled for the Goblin Tinkerer reforge menu.
As such, it is currently impossible to re-create the Goblin Tinkerer reforge menu in a mod as the only way to hide the crafting menu is to enable (and render) the vanilla reforge menu.

I propose introducing a boolean under `Main` to allow any mod to both show the player inventory and hide the crafting menu eg: `Main.HidePlayerCraftingMenu`.

### Use Cases
Any mod that wants to create an interface that interacts with the player inventory could benefit from this. `ExamplePersonUI` in v0.11 recreates the Reforge interface, but doesn't (and can't) hide the crafting menu like "real" Reforge interface does.
I'm personally making an NPC that renders a "powered up" Reforge interface, but I cannot hide the crafting menu and have to carefully avoid placing menu items near the crafting interface. Being able to hide the crafting interface would give me a lot more space for my interface.

### Versions
tModLoader v0.10.1.5

**Comment by Chicken-Bones** [comment]
While this would be possible with IL modification, I support this as a tML hook
