### ISSUE TITLE
References folder not generating

### ISSUE THREAD

**Issue by Trivaxy** [blushiemagic/tModLoader#477]
### Description
According to the migration docs, a folder named "references" containing the log4net and MonoMod's dll files should be generated in Games/Terraria/ModLoader after the game starts up for the first time, however, this does not happen.

### Steps to Reproduce
Start game, check for references folder, it won't be there.

### Expected behavior 
References folder generated upon game starting up for the first time.

### Actual behavior
No reference folder made.

### Reproduction frequency
Each time I start up the game, the folder fails to generate.

### Versions
v0.11 Beta 1

### Mods
No mods.

### Additional Information
None.

**Comment by Luiafk** [comment]
Could be useful just dumping all the references in there, makes it easier if someone wants json/relogic (they're the two common ones i can think of) dll as well.

**Comment by Trivaxy** [comment]
I believe all the references are actually put in the references folder as well, that seems to be the case in the references folder in this repo

**Comment by Chicken-Bones** [comment]
https://github.com/blushiemagic/tModLoader/commit/4805fe4721020c130616019a60b554738ac72caf

**Comment by Chicken-Bones** [comment]
![image](https://user-images.githubusercontent.com/388233/51422460-9198e080-1bfa-11e9-8753-492b033fe6d0.png)
https://pastebin.com/zATXA02P
Can be included in a csproj easily, example: https://cdn.discordapp.com/attachments/103114194089431040/536046315868651520/Skeleton.zip

**Comment by Chicken-Bones** [comment]
Currently runs on entering the Mod Sources menu, or initiating a build (whichever comes first)
