### ISSUE TITLE
Request: Mod dependency major version must equal major version specified in build.txt

### ISSUE THREAD

**Issue by hamstar0** [blushiemagic/tModLoader#478]
According to [Semantic Version](https://semver.org/) specification, major versions always indicate incompatible APIs. Mods should similarly not allow dependency mods of a mismatched major version.

**Comment by hamstar0** [comment]
But how many mods that disregard versions are counted as dependencies for other mods that also do not omit the minimum version indication? Mods that concern with being used as APIs should probably care a bit more on the matter, IMO.

**Comment by Chicken-Bones** [comment]
Give me a use-case here, and how you'd want it to work. Keep in mind that even in tML we don't just break all existing mods, we at least try to load them when a major version changes

**Comment by hamstar0** [comment]
Currently, several of my mods (ideally all of them, in time) check major versions ([example](https://github.com/hamstar0/tml-evilbarriers-mod/blob/master/MyMod.cs#L48)), as Mod Helpers tends to cause issues with major version changes, where I often remove obsolete stuff.

**Comment by hamstar0** [comment]
My check involves looking at build.txt via. reflection, though...

**Comment by hamstar0** [comment]
I *am* specifying the version in build.txt. I do that in addition to checking if the major version is mismatched.

**Comment by Chicken-Bones** [comment]
This is all well and good, but what do you /want/ to happen. Like write us out a scenario, and what you'd want a modder/user to see as error messages in each case. Then we'll see if we can work it in

**Comment by hamstar0** [comment]
Same thing that happens with a version dependency mismatch (mod version being less than the specified dependency version), only extended to major versions (being simply not equal).

**Comment by Chicken-Bones** [comment]
for weak references as well, or only references? It's not a bad idea, but it might annoy some of the larger mod devs

**Comment by Chicken-Bones** [comment]
Actually, this would only trigger if you said you wanted `LibraryMod@1.X` and instead `2.X` was installed, if you don't specify a version it accepts all yes?

**Comment by hamstar0** [comment]
My use case is only dependencies. I don't see why weak references can't apply as well.

Yes, this would only trigger if the version is specified (I don't know if any parsing for the X in `1.X` occurs with the check).

**Comment by Chicken-Bones** [comment]
https://github.com/blushiemagic/tModLoader/commit/0777545855cd2b9de1f07fbc5d70b1b751049a60
