### ISSUE TITLE
Header attribute for ModConfig

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#479]
Reminder: Applies a header before the annotated field similar to how unity does it: https://docs.unity3d.com/ScriptReference/HeaderAttribute.html

**Comment by Jofairden** [comment]
Do fields appear in-order in ModConfigs ?
I was wondering if we can do more semantic DSL for ModConfig

**Comment by Chicken-Bones** [comment]
fields do, properties do, fields and properties will not be interleaved correctly. Solution: just use properties.

**Comment by Jofairden** [comment]
Err, oops, yeah I meant properties. As for my idea, I was mentioning kotlin DSL:
```
imagine ModConfig page X

page {
    HeadingField {
       text = "My heading"
    }

    IntegerField {
        name = "The field"
        default = 1
    }
}
```
Types inferred. Page DSL accepts any `ConfigElement`, MyField is `ConfigElement<Integer>`
However, this is practically impossible in c# so properties are our best bet.

**Comment by JavidPack** [comment]
35d0e8b0f7cfb34df8c0451d80e96ba35c0b50a6
