### ISSUE TITLE
Way to force HiDef graphics profile.

### ISSUE THREAD

**Issue by chatrat12** [blushiemagic/tModLoader#488]
Working on Terraria3D. Once I made my shaders a little more complex, it wasn't hard to pass the maximum shader instructions in SM2, I had to upgrade to SM3. Unfortunately, Reach does not support SM3. More complex shaders require a way to force Terraria into HiDef. Unfortunately this can only be done before the base game starts loading its own content. 

Wrote the stuff below first but just came up with a better idea. Can we enable HiDef by default if the graphics device can handle it? There is no advantage to defaulting to reach. 

Been pondering ways to do this. I think the simplest and most straight forward way is to just enable HiDef if the graphics device can support it. There is no advantage to using Reach by default if the machine is capable of HiDef.

I can still let the user, use reach mode but with less shader features and I can do inform them of that if the game was not able to boot with HiDef enabled.

**Comment by Chicken-Bones** [comment]
Seems sound, please submit a pull request.
