### ISSUE TITLE
GitHub mod syncing seemingly broken.

### ISSUE THREAD

**Issue by Agrair** [blushiemagic/tModLoader#494]
### Description

Mods are not stored as releases on GitHub.

### Steps to Reproduce

Build, publish, etc.

### Expected behavior 

The mod appears with the appropriate release tag.

### Actual behavior

After a day, nothing happens.

### Reproduction frequency

I've release three more versions of my mod [Inventory Tweaks](https://github.com/Agrair/InvTweaks) onto the Mod Browser, but if you check the GitHub it says there's only one.

### Versions

tModLoader 0.1.10.15

### Additional Information

Sometimes, I can't find my mod on the in game browser.

**Comment by JavidPack** [comment]
According to my records you linked this github not that github: https://github.com/Agrair/VerifyWalls

Go to the mod browser site again an use change github authorization to update it
