### ISSUE TITLE
ModPack List Description Swapped

### ISSUE THREAD

**Issue by nagt06** [blushiemagic/tModLoader#497]
Description

When viewing a ModPack's Mod list, it says that the ones you have enabled are disabled, and the ones you have disabled are not disabled.

Steps to Reproduce

1. Launch Modded Terraria
2. At the menu, click "Mods"
3. Click "ModPacks"
4. View a List of a ModPack's mods
5. Check to see if they're actually disabled or not

Expected behavior

To say that the disabled mods are disabled, enabled mods are enabled

Actual behavior

The opposite, the enabled ones saying disabled, and the disabled ones saying enabled.

Reproduction frequency

From my experience, 100%

Versions

tModLoader v0.10.1.5

Mods

Disabled all, and it says they're not disabled.
Had Calamity on, it said Calamity was disabled.

Additional Information

I'm using the Mac version of tModLoader and Terraria.

**Comment by JavidPack** [comment]
Thanks a lot for the report, fixed in next release.
