### ISSUE TITLE
tModLoader v0.11 Mac Beta 2 Missing Files

### ISSUE THREAD

**Issue by nagt06** [blushiemagic/tModLoader#498]
**Note: This is all on the mac version of tModLoader.**

**Description**
Not in-game; It's the zip file. It's missing 4 files, more specifically:
Ionic.Zip.Reduced.dll
Mono.Cecil.dll
MP3Sharp.dll
tModLoaderServer.bin.osx

Which is found in Beta 1 but not Beta 2.

**Steps to Reproduce**
1. Download tModLoader v0.11 Beta 1
2. Download tModLoader v0.11 Beta 2
3. Open both zip files
4. Compare the files that exist and are missing

**Expected behavior** 
The zip file for tModLoader v0.11 Beta 2 should have all files for the installation.

**Actual behavior**
The zip file for tModLoader v0.11 Beta 2 is missing these files:
Ionic.Zip.Reduced.dll
Mono.Cecil.dll
MP3Sharp.dll
tModLoaderServer.bin.osx

**Reproduction frequency**
Downloaded Beta 2 like 3 times to make sure, and 100%

**Versions**
Simply just tModLoader v0.11 Beta 2

**Mods**
This probably doesn't even matter, but none.

**Additional Information**
Beta 1 worked PERFECTLY FINE on mac, and beta 2 just simply crashed even before the window pops up. Must be related to the installed files.
UPDATE: I moved the beta 1 files of the 4 files to beta 2 then installed, and it worked. I'm going against a problem with a mod generating "ruines", but that's a mod problem...

EDIT: The dll files and such were imbedded in terraria.exe. After installing Beta 2, removing Mono.Cecil.dll, Ionic.Zip.Reduced.dll, and MP3Sharp.dll from Terraria.app/Contents/MacOS fixed the problem, and now is working fine.

Keep up the good work on tModLoader v0.11!

**Comment by JavidPack** [comment]
Thanks. Removing those files is on purpose, as they are now embedded in the exe itself. Sounds like it isn't working as expected, however. If you could show the output when running `./Terraria` from the command line in that folder, that would help me figure out where things are going wrong.

We regularly discuss and test the beta in the discord chat, the `#beta` channel. If you are on discord, chatting there would accelerate how quickly we can diagnose this issue, but here is also fine.

**Comment by nagt06** [comment]
Alright, I joined the server. It's gonna take a bit to become a member, but I'll ask you what to do to see the output so I can show it. Thanks!

**Comment by JavidPack** [comment]
After some troubleshooting, we discovered that Mono.Cecil.dll from previous installations of tModLoader seems to cause issues. We should update the installer to delete the 3 dlls we embedded and update the readme.txt to mention deleting those files for manual install instructions

**Comment by nagt06** [comment]
Yup, deleting Ionic.Zip.Reduced.dll, Mono.Cecil.dll, and MP3Sharp.dll solved the problem.
