### ISSUE TITLE
I cannot update mods

### ISSUE THREAD

**Issue by jvschiavo** [blushiemagic/tModLoader#499]
### Description
I cannot update mods (at least Recipe Browser)

### Steps to Reproduce
1. Have Recipe Browser v0.7.1
2. Open Mod Browser, search for "Recipe ", and click update on the v0.7.1.2

### Expected behavior 
It should update.

### Actual behavior
It doesn't work.

I click update:
![20190225180128_1](https://user-images.githubusercontent.com/20977075/53374346-c9502200-3936-11e9-8a2e-92d4abc6fd42.jpg)

It shows it is downloading it:
![20190225180134_1](https://user-images.githubusercontent.com/20977075/53374384-e8e74a80-3936-11e9-9f97-c773cf1b912d.jpg)

Nothing has changed:
![20190225180139_1](https://user-images.githubusercontent.com/20977075/53374397-f0a6ef00-3936-11e9-8dcf-40193f0ef591.jpg)

### Reproduction frequency
Always

### Versions
Terraria v1.3.5.2
tModLoader v0.11 Beta 1

### Mods
Calamity Mod (No Calamity Music) v1.4.1.4
Calamity Mod Music v1.4.1.3
Recipe Browser v0.7.1 (trying to update to v0.7.1.2)
(Disabled) Mod Helpers v4.2.2.1

### Additional Information
By alt+tabbing I realize I get a window pop-up error:
![tmodloader_error](https://user-images.githubusercontent.com/20977075/53374463-277d0500-3937-11e9-8fbd-11935d5d557c.png)

These are the details of the error (sorry it being in portuguese):
https://pastebin.com/raw/xRTWk9rb

If I try to Update All I get the same error but I cannot get out of this screen, I have to force close Terraria instead:
![20190225181159_1](https://user-images.githubusercontent.com/20977075/53374685-c9045680-3937-11e9-824e-581e0e0f2eda.jpg)

**Comment by VitinhoCarneiro** [comment]
The error message says there's another process on your computer using the Recipe Browser mod file.

Have you tried rebooting your computer? There might be a stray process locking the file from being updated, and that might solve the problem.

**Comment by JavidPack** [comment]
This is a known bug if beta 1. Please use beta 2 or disable and reload mods before updating

**Comment by jvschiavo** [comment]
Yay, it worked! I'm sorry, I didn't know beta 2 was already released. Thank you!
