### ISSUE TITLE
Add tags to town npc/and any other text missing the feature.

### ISSUE THREAD

**Issue by OSBooter** [blushiemagic/tModLoader#501]
**Description**
Well I'm looking for more flexibility in the string text for town npc modding. Like emojis and item icon usage where for now is just plain text.

I'd like tag support to go into that somehow, I would suppose it would be similar to how tag works in items and chat, and of course if there are any other text that I've overlooked that may benefit from this feature.

**Use Cases**
Finishing quests from town npcs could explicitly show what you will get, or point to multiple items to collect instead of just using the **Main.npcChatCornerItem** that is delightfully useful  and yet limited in the angler npc.
And also would allow less text over-saturation such as keeping npc chat boxes from growing and moving the buttons erratically.

**Versions**
tModLoader v0.10.1.5

**Comment by Chicken-Bones** [comment]
I'm in favour of this, but can mods not just make their own NPC chat guis?

**Comment by Agrair** [comment]
They can, but I can see why this would help.
