### ISSUE TITLE
Mods build with dependency-mismatch warnings after upgrading TerrariaHooks to Mono.Cecil 0.10.3

### ISSUE THREAD

**Issue by tansheron** [blushiemagic/tModLoader#508]
Repro steps:

* Build tModLoader, tModLoaderServer and tModLoaderMac
* Convert MonoMod and TerrariaHooks to use Mono.Cecil 0.10.3
* Replace TerrariaHooks' reference to Terraria with the newly-built tModLoader
* Build MonoMod and TerrariaHooks using the newly-built tModLoaderServer and tModLoaderMac
* Open TerrariaHooks.Windows.dll in ILSpy and observe that it depends on both Mono.Cecil 0.10.3 and 0.9.6
* Build a simple mod which depends on the newly-built tModLoader and TerrariaHooks

Expected result:

* Mod builds without warnings

Actual result:

* Mod builds with the warning "No way to resolve conflict between "Mono.Cecil, Version=0.10.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e" and "Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756". Choosing "Mono.Cecil, Version=0.10.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e" arbitrarily."

Frequency: 100%
Version: v0.11 beta 3 - commit 6c497630587cf2e7c39d9e6290cd6cc2801a3e27

I suspect that the problem occurs because tModLoader and the generated TerrariaHooks dlls have a circular dependency on each other. If one is rebuilt, it will inherit the other's Mono.Cecil dependency. Binding redirections will do nothing because 0.9.x and 0.10.x have different public-key tokens.

Maybe TerrariaHooks needs to be able to generate dlls which don't depend on tModLoader?

**Comment by tansheron** [comment]
There are a lot of steps involved in updating tModLoader and TerrariaHooks together. I missed one while updating TerrariaHooks for Mono. The warning is fixed now.

**Comment by Chicken-Bones** [comment]
Feel free to come have a chat on Discord, just ping me
