### ISSUE TITLE
Bosses don't spawn when I am not the host of a multiplayer world

### ISSUE THREAD

**Issue by TheDeathLord3** [blushiemagic/tModLoader#510]
Every time I try to spawn a boss (both modded and vanilla) the boss makes the spawning noise but never appears when I am on my friend's multiplayer hosted world. Certain bosses get "replaced" with another monster for some reason and despawns after flashing on screen for a second. When he tries to spawn the boss, it works just fine. We also tried this in vanilla and boss spawning worked.

Steps to Reproduce
1. Have someone else host the world
2. Join the and try to spawn in the boss

### Expected behavior 
The boss spawns
### Actual behavior
Boss doesn't spawn and it uses the spawn item
### Reproduction frequency
Every time I try to spawn a boss.
### Versions
tModLoader v0.10.1.5 (MAJOR?)

### Mods
Alchemist NPC
Antiaris
Antisocial
Auto Trash
Boss Checklist
Build Planner
Calamity
Calamity music
Dual Wielding
Exodus
Extensible Inventory
Fabus
Fargowiltas
Fargowiltas Souls
HamstarHelpers
Inlustris
Instant Respawn
Laugicality
Luiafk
Magic Storage
Max Stack Plus
More Accessories
No More Tombs
Pumpking
RecipeBrowser
Reforge Armor
Sacred Tools
Simple auto Chest
Split
Summoners Association
Tremor (WE tried with out it and it didn't effect results)
Valkyries Content Crate
Wing Slot
What Mod Is This From

### Additional Information
None

**Comment by JavidPack** [comment]
We can't really test this sort of thing. Sounds like a mod or a combination of mods is causing issues. You'll need to follow the flowchart until you can identify the mod of pair of mods that causes the issue. After that, you need to contact the developers of those mods, not us.

Flowchart:
https://github.com/blushiemagic/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart
