### ISSUE TITLE
cs1002 error

### ISSUE THREAD

**Issue by ThatCodingGuy8** [blushiemagic/tModLoader#511]
### Description
When I try to set InstancePerEntity for a globalNPC, it says it's missing a semicolon, when I clearly included a semicolon. I even copy and pasted the one from the exampleGlobalNPC and it did an error.

### Steps to Reproduce

1. Make a new globalNPC class
2. Put this code within the class: public override bool InstancePerEntity => true;
3. Run tmodloader and try to build the mod

### Expected behavior 
It SHOULD be completely fine but it gives a semicolon error when there is clearly a semicolon

### Actual behavior
It won't compile because it doesn't think there is a semicolon there when there is one clearly there

### Reproduction frequency
Every time

### Versions
tModLoader v0.10.1.5

### Mods
N/A, won't get past building screen for custom mod

### Additional Information
C# language is 4
Full code:

```
using Microsoft.Xna.Framework;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Terraria;
using Terraria.ModLoader;
using Terraria.ModLoader.IO;
using Terraria.Utilities;

namespace Set8
{
    public class GlobalOneNPC : GlobalNPC
    {
        public override bool InstancePerEntity => true;

        public bool sunburn;

        public override void ResetEffects(NPC npc)
        {
            sunburn = false;
        }

        public override void UpdateLifeRegen(NPC npc, ref int damage)
        {
            if (sunburn)
            {
                npc.life = npc.life - 5;
            }
        }
    }
}
```

**Comment by JavidPack** [comment]
Fixed in chat. The issue was the c#6 style code used in recent ExampleMod code. You can select the 0.10.1.5 tag while in github to see old style code for examplemod.
