### ISSUE TITLE
Sprite Offset for useStyle = 1 weapon

### ISSUE THREAD

**Issue by KJay05** [blushiemagic/tModLoader#514]
In-game, whenever my character swings the weapon, you can see that the weapon sprite is a small distance away from the actual hand itself. I want to find out how to make an offset for the weapon, which would results in the weapon sprite actually being on the character's hand.

![image](https://user-images.githubusercontent.com/49630551/56108504-a4b81400-5f8f-11e9-8109-c6c903e264d5.png)

### Expected behavior 

The weapon sprite to be shown like it is held on the player's hand

### Actual behavior

The weapon sprite is a small distance away from the hand

### Versions
tModLoader v0.10.1.5

![image](https://user-images.githubusercontent.com/49630551/56108484-818d6480-5f8f-11e9-98de-6216786ebdce.png)

My sprite is cropped perfectly. I want to make the offset, because I have a slightly large weapon that is causing the issue. I want to find a way to keep the weapon size but still move the sprite onto the hand. I've seen ExampleMod, asked on Discord multiple times, still no answer. ExampleMod shows how to make an offset for a useStyle = 5 gun/staff, but it does not work with useStyle = 1 weapons.

Sorry if this is in the wrong place, or anything else, I'm both new to tModLoader modding and GitHub.

**Comment by Jofairden** [comment]
Is the item.Size the same as the sprite size? Make sure it is first and check

**Comment by Jofairden** [comment]
@KJay05 did it solve the problem?

**Comment by KJay05** [comment]
I had tried it before, nothing worked. I just decided to compress the
pixels a bunch, then scale it to be large, even though it looks a bit worse
