### ISSUE TITLE
Files with capitalized extensions not accounted for

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#515]
If a file, for example MyWeapon.PNG, has capital letters in the extension, it won't be packed into the mod.

**Comment by Chicken-Bones** [comment]
Should people just lowercase them?

**Comment by Jofairden** [comment]
It should work fine, at least on Windows file extensions are case insensitive. In code you're supposed to do EqualsIgnoreCase to mitigate these issues.

**Comment by Jofairden** [comment]
87cf325dc9c9cf5cc064f2e51a464bf94e5e936a
I think this should be fine, I don't see any usecase for when a modder would want the same file with case-sensitivity differences. Keys in dictionaries are compared ignoring case. I added some .ToLower() calls to ignore case for extension checks.

**Comment by Chicken-Bones** [comment]
Should be fine in this instance, though case insensitive paths being different between windows/linux is sometimes a debate of controversy. I think there's not a lot of reason /for/ things to be case insensitive, especially as most things programming are case sensitive
