### ISSUE TITLE
Extra dlls for RoslynWrapper/ModCompile

### ISSUE THREAD

**Issue by Chicken-Bones** [blushiemagic/tModLoader#516]
Some users are unable to build mods on windows due to missing the following dlls:
```
System.IO.FileSystem.dll
System.IO.FileSystem.Primitives.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
```
Most users have these in the GAC. We may consider just adding these to the ModCompile list. The total size of these libraries is 166KB

**Comment by Jofairden** [comment]
The size is so small, just add them. Anything under 1MiB isn't even worth discussing imo.
