### ISSUE TITLE
Client Main.NewText

### ISSUE THREAD

**Issue by wooden-utensil** [blushiemagic/tModLoader#518]
Hi.
I was wondering if `Main.NewText` would run on just the client or all the clients, I'm running `Main.NewText` in the `Action` function in `MyCommand`. `MyCommand` is inherited from `ModCommand`.
Thanks.

**Comment by Jofairden** [comment]
I'm fairly sure Main.NewText always runs only locally. If you want to send it to all clients, it will have to be sent via a network packet.

**Comment by wooden-utensil** [comment]
> I'm fairly sure Main.NewText always runs only locally. If you want to send it to all clients, it will have to be sent via a network packet.

Thanks!
