### ISSUE TITLE
Feature Request: Add Mod Memory Reporting

### ISSUE THREAD

**Issue by zauberparacelsus** [blushiemagic/tModLoader#519]
I'm one of those users who installs a *lot* of mods.  I install enough that I have to think before I install another mod, so as to avoid Terraria using too much memory.

However, aside from enabling/disabling my mods one-by-one and checking memory usage each time, the only method I have to go by is looking at the file sizes.  This is a very flawed method however, as the files (I assume) include a lot of compressed data.  As I've found, Calamity has a higher impact on memory than Sacred Tools, despite the SacredTools.tmod being nearly twice as large as CalamityMod.tmod.

So, what I'd like to see is some feature that allows tmodloader to report the memory usage of each individual mod, so that I can make a more informed decision on which mods to remove when I am trying to cut down.

**Comment by Jofairden** [comment]
The new beta already has this feature. If you like to try it then download the beta.
