### ISSUE TITLE
tModLoader server console out of date

### ISSUE THREAD

**Issue by wooden-utensil** [blushiemagic/tModLoader#523]
### Description
tModLoader server console is currently at v0.10.1.4, but the latest tModLoader is v0.10.1.5, which makes it unusable

### Steps to Reproduce
1. Upgrade to v0.10.1.5
2. Open server

### Expected behavior 
Server should be at v0.10.1.5

### Actual behavior
Server is at v0.10.1.4

### Reproduction frequency
100%

### Versions
tModLoader v0.10.1.4/5

**Comment by Jofairden** [comment]
I think this is your own mistake. The server is at 0.10.1.5 if you download that version, are you sure you downloaded the correct version?

**Comment by wooden-utensil** [comment]
Hm? Weird
