### ISSUE TITLE
tModLoader Host and Play gets stuck on "Starting server..."

### ISSUE THREAD

**Issue by Zoophlas** [blushiemagic/tModLoader#524]
### Description
When I try to host a server using "Host and Play" in-game, after defining all of the settings I want to use on the server, the server starts to load but shows "Starting server..." and never loads into the actual game.

### Steps to Reproduce
1. Click multiplayer
2. Click host and play
3. Select character
4. Select world
5. Define server settings
6. Enter server password
7. Start server

### Expected behavior 
The server should start up and after the server finishes loading I should be put into the world with my selected character

### Actual behavior
Terraria just sits there with the text "Starting server..." displayed on the screen.

### Reproduction frequency
100%

### Versions
tModLoader v0.10.1.5

### Mods
I've tested with and without any mods enabled and I still get the same issue. But if it helps here are the mods that I use:
Thorium Mod v1.6.0.0
More Chest Loot v0.6
No More Tombs v1.0.1
MaxStacksPlus v21.0
VeinMiner v1.3.0.5
Calamity Mod v1.4.2.4
Calamity Music Mod v1.4.2.1
AlchemistNPC v8.4
Recipe Browser v0.72
Dragon Ball Terraria v1.0.9.3
Boss Checklist v0.2.1
JPAN's Bags of Holding v1.4
Universe of Swords v2.8
Wireless v1.5
SuperQuickRespawn v1.0.1
Tremor Mod Remastered v1.3.2.7
Yet Another Boss Health Bar v1.3.2
More Endless Ammo v1.0.0.1
Wing Slot v1.6.2

### Additional Information
I have tried reinstalling tModLoader multiple times. I have redownloaded tModLoader from the GitHub release multiple times and have had no improvement. I've tried using the tModLoaderServer.exe and the start-tModLoaderServer(-friends/private).bat and have had no luck. I've purged all of my Terraria files and tried the vanilla version and got it to work, but when I reinstalled tModLoader it stopped working. I've checked my AntiVirus and all necessary tModLoader files are excluded and the default server port is excluded from my AntiVirus as well.

**Comment by Jofairden** [comment]
So the dedicated .exe is also stuck on "Starting server... " ?

**Comment by wooden-utensil** [comment]
Try disabling each mod one by one, and as soon as it works, report the last one that you disabled.

**Comment by Zoophlas** [comment]
> 
> 
> So the dedicated .exe is also stuck on "Starting server... " ?

It appears to load completely but I cannot join.

**Comment by Zoophlas** [comment]
> 
> 
> Try disabling each mod one by one, and as soon as it works, report the last one that you disabled.

OK. So I did what you suggested and the issue seems to be revolving around Thorium. I don't know why it wouldn't work whenever I had all the mods disabled but disabling it fixes the issue. It still takes longer than I remember but thats probably because of the mods loading or something. Thank you for your help though.

**Comment by Jolteon1234amongus** [comment]
i have different mods than you but this happens to me a lot but sometimes it just works and I dont have to remove anything it's really weird and then other times I'm stuck on "Starting Server" for 2 hours and nothing happens i wish I could see like a server progress loading bar it would be me feel so much better

**Comment by Chicken-Bones** [comment]
Added #3317 as a feature request
