### ISSUE TITLE
Mod downloads be asynchronous

### ISSUE THREAD

**Issue by TheOnlyMrCat** [blushiemagic/tModLoader#529]
### Suggestion:
Have mod downloads be asynchronous. I recently had to redownload my mods, and I would like to be able to queue up a lot of downloads while searching for my mods.

**Comment by Jofairden** [comment]
I am currently already working on this. In fact, it has already been made async. Look forward to it in the future releases.

**Comment by Jofairden** [comment]
I'll close this via commit later
