### ISSUE TITLE
Change player opacity with buff

### ISSUE THREAD

**Issue by wooden-utensil** [blushiemagic/tModLoader#530]
### Description
Hello.
So you know the invisibility potion ![Invisibility potion](https://gamepedia.cursecdn.com/terraria_gamepedia/c/c1/Invisibility_Potion.png?version=843afc22167922c96c5442b773d7e0cc), how it makes you _invisible_ when you drink it, well is it possible to recreate that in a buff. For example:
```cs
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace _______.Buffs.____ {
    public class ExampleBuff : ModBuff {
        public override void SetDefaults () {
            DisplayName.SetDefault ("____");
            Description.SetDefault ("_______________");
            Main.buffNoTimeDisplay[Type] = true;
        }

        public override void Update (Player player, ref int buffIndex) {
            player.Opacity = 0.0f; // Make invisible here
        }
    }
}
```

### Additional information
This is an idea

**Comment by Jofairden** [comment]
I don't really understand the purpose of this post. Please only post actual issues with the API here.

**Comment by wooden-utensil** [comment]
Yeah you're right I should post it on the forums. Okay brb.
