### ISSUE TITLE
Linux Mod Browser not working 0.11 Beta 4

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#534]
Report from Discord by Talchas:

> on linux the download of a mod is instantly aborting or something, I get ~1 frame of the download window, and the log says "[17:01:12] [Threadpool worker/INFO] [tML]: DownloadManager handling new download"

**Comment by Jofairden** [comment]
Something is off with the threadpool/manager on linux. May have to do with the synchronization context or something like that.

**Comment by Chicken-Bones** [comment]
should be fixed in beta 6
