### ISSUE TITLE
Player.allDamage behaviour is inconsistent with vanilla

### ISSUE THREAD

**Issue by DarkLight66** [blushiemagic/tModLoader#543]
### Description
`Player.allDamage` acts as a multiplier to the current class damage, instead of being added to it.
To put an example, using a melee weapon that deals 100 damage, while having equipment that increases melee damage by 50%, and all damage by 50%, would result in 225 damage done instead of 200. The problem lies in that, with the addition of the `allDamage` field, all instances in the `Player` class where all five damage types where increased at the same time were replaced by the `allDamage` field. This ends up being inconsistent as in most of those instances damage was being added rather than multiplied.

### Steps to Reproduce
1. Use equipment and buffs that increase damage for a specific damage type or all damage types at the same time
2. Attack an enemy with a weapon affected by the damage bonuses

### Expected behavior 
Damage done stays consistent with vanilla

### Actual behavior
Damage done is larger than in vanilla, with the difference being larger as more damage bonuses are used

### Reproduction frequency
Always

### Versions
`tModLoader v0.11 beta 4`

### Mods
None

### Additional Information
`Player.allDamage` was added in commit ac85f2e , which clossed issue #502

**Comment by JavidPack** [comment]
Hm, looks like we are multiplying twice here: https://github.com/blushiemagic/tModLoader/blob/master/patches/tModLoader/Terraria/Player.cs.patch#L4946

We'll need to add the 2 multipliers, then multiply last.

**Comment by Jofairden** [comment]
Yep, or just change the allDamage setter to modify vanilla multipliers directly? Since it's exactly the same.
Though then it wouldn't really work for "custom" damage.

**Comment by Chicken-Bones** [comment]
This cannot be fixed without breaking changes, the closest we could get is to make `allDamageAdditive` and `allDamageMultiplicative` but it still won't stack correctly in some scenarios, See https://github.com/blushiemagic/tModLoader/issues/503

**Comment by Chicken-Bones** [comment]
Sorry, didn't read the report correctly, it is a bug that we're altering vanilla behaviour.

**Comment by Jofairden** [comment]
We're not altering vanilla behavior, it is a bug on our end. We're not supposed to multiply beforehand, we're supposed to add the allDamage during the multiplication of the vanilla multipliers like jopo said.

**Comment by Jofairden** [comment]
Fixed in https://github.com/blushiemagic/tModLoader/commit/3777cffa190faa4c8a76441b5b0590aa523da525 
and https://github.com/blushiemagic/tModLoader/commit/8c714d7f7dc9993d515c8e3d8531397b4f754506
