### ISSUE TITLE
Mod Browser Crashing

### ISSUE THREAD

**Issue by DarkPoke** [blushiemagic/tModLoader#549]
### Description
 When in game, I press mod browser, and the game proceeds to crash. 

### Steps to Reproduce

1. Launch game
2. Click Mod Browser 
3. Crash 
*Seems to only crash after the first time launching mod browser and installing mods
### Expected behavior 

Should boot up mod browser to find and install mods.
### Actual behavior

When clicking on mod browser, game proceeds to crash.
### Reproduction frequency
 
It seems it happens every time except the first time before installing any mods?
### Versions
 tModLoader v0.11 Beta 5, Terraria v1.3.5.2

### Mods

Calamity Mod (Without Music)
Calamity Mod Music
Mod Helper
Yet another boss bar
Instant respawn
Item Checklist 
Magic Storage
### Additional Information
 Crash log (Appears when you press Mod Browser), also Mods tab isn't responsive to cursor, but search function works.
![Screenshot_2](https://user-images.githubusercontent.com/39809832/58999237-a21cb280-87b9-11e9-8428-43d4e45781cf.png)

**Comment by DarkPoke** [comment]
And I just realized I used a beta version without reading that it'll crash. That's my bad.

**Comment by Jofairden** [comment]
This is also not a problem in tModLoader, just to remind you about that. It's HamstarHelpers mods here causing the error, which you can see in the error.
