### ISSUE TITLE
Error Building with Reference - Trying to Load an Assembly from Web

### ISSUE THREAD

**Issue by strongrex2001** [blushiemagic/tModLoader#552]
### Description
Building a mod with reference to another one, and an error comes.

### Steps to Reproduce
I've tried on several different PCs. Only one runs into the error, so I'm not sure how to reproduce.

### Expected behavior 
Compile smoothly.

### Actual behavior
```plain
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Terraria.ModLoader.ModCompile.RoslynCompile(CompilerParameters compileOptions, String[] files)
   at Terraria.ModLoader.ModCompile.CompileMod(BuildingMod mod, List`1 refMods, Boolean forWindows, Byte[]& dll, Byte[]& pdb)
   at Terraria.ModLoader.ModCompile.Build(BuildingMod mod, IBuildStatus status)
   at Terraria.ModLoader.ModCompile.Build(String modFolder, IBuildStatus status)
   at Terraria.ModLoader.ModLoader.<>c.<BuildMod>b__74_0(Object _)
```
When building.

### Reproduction frequency
100% on that specific PC, 0% on others.

### Versions
0.10.0.5

### Mods
No other mods enabled. An empty mod with reference also runs into this error.

### Additional Information
Since it is not built in Visual Studio, I don't know how to turn on 'loadFromRemoteSources' switch.
Reinstalled .NET framework but nothing happened.
Maybe changing the loading code into
```csharp
byte[] assemblyBuffer = File.ReadAllBytes(path);
Assembly a = Assembly.Load(assemblyBuffer);
```
Could solve the problem

**Comment by Chicken-Bones** [comment]
Is there no way we can just updatw pwrmissions before building jopo?

**Comment by JavidPack** [comment]
This issue is documented here: https://github.com/blushiemagic/tModLoader/wiki/Basic-tModLoader-Modding-FAQ#c-6-issues-an-attempt-was-made-to-load-an-assembly-from-a-network-location

Basically it's an install issue, and already avoided in 0.11, so no further action is needed.

**Comment by Chicken-Bones** [comment]
But can we detect this and just wipe the folder automatically?
