### ISSUE TITLE
Cannot extract .wld files

### ISSUE THREAD

**Issue by Benzillaist** [blushiemagic/tModLoader#553]
### Description

Go to your backup folder and try to copy files from the backup folder to the main "Worlds" folder
1. [First Step]
2. [Second Step]
3. [And so on...]

### Expected behavior 

I think that the file should be extracted from the zipped folder and fully copied to the Worlds folder.
### Actual behavior

I get the error posted above.
### Reproduction frequency

100% of the time
### Versions

currently, I am using tModLoader v0.11 Beta 5
### Mods

(I don't think that the mods matter)
Elements Awoken Music
Fargo's Mutant Mod
Magic Storage
OmniSwing
VeinMiner
Recipe Browser
Calamity Mod Extra Music
Cheat Sheet
Calamity Mod Music
Calamity Mod (No Calamity Music)
Fargo's Soul Mod
Elements Awoken
Boss Checklist
AFK's PETS and more
### Additional Information

Yesterday, when I last played, I hard shut down my computer without fully exiting Terraria, I exited and saved my world, but I stopped my computer when Terraria was in the main menu.
[2019-06-12-Modpack_Neat.zip](https://github.com/blushiemagic/tModLoader/files/3288356/2019-06-12-Modpack_Neat.zip)

**Comment by Jofairden** [comment]
I'm not sure about this issue, you're a bit vague. What exactly are you trying to extract? Is this about a bug in tModLoader?

**Comment by JavidPack** [comment]
I think this is an actual bug. I think the issue might be with the zip file. I can extract the contents fine with 7zip, but with the windows explorer unzip I too get an error:     
![](https://i.imgur.com/KrQ55rI.png)

**Comment by JavidPack** [comment]
Players also suffer from this problem. Log backups extract without issue.

**Comment by Jofairden** [comment]
We used BZIP compression, but explorer only supports DEFLATE for some reason....

**Comment by Benzillaist** [comment]
So how would I extract files using BZIP compression?

**Comment by Benzillaist** [comment]
Thank you!
