### ISSUE TITLE
Expanding ModNPC SetChatButtons & OnChatButtonClicked

### ISSUE THREAD

**Issue by Phantom139** [blushiemagic/tModLoader#67]
At the current moment, the ModNPC class only allows you to define two Chat options, where most of the time the first of which is set as a "Shop", leaving you with only one other option to define. This is very limiting in many circumstances.

My suggestion is to make a minor adjustment to these two methods. 

For SetChatButtons, change it from (ref string button, ref string button2) to (ref string[] buttons). A more viable limit could then be applied (5 - 6 should be optimal). For OnChatButtonClicked, it would change from (bool firstButton, ref bool isShop) to (int buttonIndex, ref bool isShop).

This would open up a lot more in terms of NPC functionality for modders and custom town bots.

**Comment by Agrair** [comment]
Holy crap that's actually a good idea.

**Comment by Chicken-Bones** [comment]
This one's getting archived due to lack of interest. It was a solid proposal, and can be revived with ongoing discussion, but for now, there's always IL editing
