### ISSUE TITLE
Lag with wrapped text in mod descriptions

### ISSUE THREAD

**Issue by gamrguy** [blushiemagic/tModLoader#74]
When viewing a mod description where the text wraps to the next line (because there wasn't a newline character and it would've gone out of the box otherwise) the framerate drops significantly. This is compounded the more text wrapping exists in the mod description.

Descriptions that use newline characters to avoid this do not experience this issue.

**Comment by JavidPack** [comment]
Can you tell me an example of a mod description that causes the problem? I can't seem to replicate.

**Comment by gorateron** [comment]
I cannot seem to replicate this bug either, and I've went over more than a dozen mods with very large descriptions.

**Comment by gamrguy** [comment]
Perhaps this is due to my subpar hardware, then... or it could be related to being on Linux. My guess is leaning more towards the former than the latter, however.

Regardless, the amount of lag I am experiencing is unusually high. An example of a mod description which does this for me is Cheat Sheet - but I'm sure any reasonably powerful computer by today's standards would have no problem (and mine is far from that).

**Comment by Jofairden** [comment]
@gamrguy So you're on Linux? Can you try and test vanilla UI (so launching the vanilla UI) and see if there are any FPS drops? Can you then afterwards try reinstalling tML and test again? I still can't seem to replicate your issue, although I'm on Windows, not Linux.

**Comment by Jofairden** [comment]
Bug persists, happens on Tremor Mod Remastered for version 1.3.1.15 in the mod browser, with the following description.txt provided:

> Tremor mod is one of the biggest Terraria mods.
> 
> The latest version of mod includes:
> 
> -Over 1500 new items - including new armor sets, weapons for each class, accessories, new materials and banners for every mob.
> -17 new bosses - every boss has it's own AI, loot, treasure bag with unique expert item.
> -13 new NPCs - each NPC has it's own stuff to sell. Many NPCs also sell new things after certain bosses are defeated.
> -2 brand new invasions - new invasions with new interesting mobs, loot and also with new soundtracks.
> -New Glacier minibiome - a biome that spawns in Snow biome and has new mobs and loot.
> -New ores - some generate in the beginning of the game and some only generate after defeating certain boss.
> -Ruins structure - a new structure that generates underground with new mobs, chests, loot and boss!
> -Tremode - Post Moon Lord gamemode with it's own ores, lots of new content, such as armors, weapons, materials, harder monsters and hard bosses.
> -New alchemist class - absolutely new class with new damage type, weapons, armor and accessories.
> -New Nova Celestial Pillar - a completely new pillar for alchemist class that spawns with regular pillars!
> -11 new soundtracks - amazing tracks for different bosses and events made by Delicious Saturn.
> -Amazing neat sprites made by our wonderful spriters!
> -And also support of Boss Checklist Mod!

At render, <br> tags are shown, fps drops to 1-2
![](https://images.discordapp.net/attachments/107584307517751296/334390790375866368/unknown.png?width=1284&height=678)

**Comment by Jofairden** [comment]
Fixed in 3ed0aed
